// AUTO-GENERATED by scripts/generate-fifty-stop-demos.mjs — do not edit by hand
import type { MultiStopDemoSeed } from './multiStopDemoTypes';

export const FIFTY_STOP_DEMOS_BY_REGION: Record<string, MultiStopDemoSeed[]> = {
  "seattle": [
    {
      "address": "400 Broad St, Seattle, WA 98109",
      "lat": 47.62019,
      "lng": -122.3493,
      "duration": 0
    },
    {
      "address": "85 Pike St, Seattle, WA 98101",
      "lat": 47.60871,
      "lng": -122.34056,
      "duration": 10
    },
    {
      "address": "1501 Pike Pl, Seattle, WA 98101",
      "lat": 47.60873,
      "lng": -122.3406,
      "duration": 10
    },
    {
      "address": "1928 Post Alley, Seattle, WA 98101",
      "lat": 47.61059,
      "lng": -122.34279,
      "duration": 15
    },
    {
      "address": "601 E Pike St, Seattle, WA 98122",
      "lat": 47.61408,
      "lng": -122.32415,
      "duration": 10
    },
    {
      "address": "1427 Broadway, Seattle, WA 98122",
      "lat": 47.6133,
      "lng": -122.32081,
      "duration": 10
    },
    {
      "address": "1301 Madison St, Seattle, WA 98104",
      "lat": 47.6105,
      "lng": -122.32242,
      "duration": 15
    },
    {
      "address": "999 Third Ave, Seattle, WA 98104",
      "lat": 47.60531,
      "lng": -122.33452,
      "duration": 20
    },
    {
      "address": "700 5th Ave, Seattle, WA 98104",
      "lat": 47.60495,
      "lng": -122.33009,
      "duration": 10
    },
    {
      "address": "1201 3rd Ave, Seattle, WA 98101",
      "lat": 47.60739,
      "lng": -122.33566,
      "duration": 15
    },
    {
      "address": "4500 University Way NE, Seattle, WA 98105",
      "lat": 47.66143,
      "lng": -122.31311,
      "duration": 10
    },
    {
      "address": "1410 NE Campus Pkwy, Seattle, WA 98105",
      "lat": 47.65621,
      "lng": -122.31276,
      "duration": 10
    },
    {
      "address": "4735 University Way NE, Seattle, WA 98105",
      "lat": 47.66445,
      "lng": -122.31353,
      "duration": 15
    },
    {
      "address": "3621 Fremont Ave N, Seattle, WA 98103",
      "lat": 47.65205,
      "lng": -122.34992,
      "duration": 10
    },
    {
      "address": "3417 Fremont Ave N, Seattle, WA 98103",
      "lat": 47.65008,
      "lng": -122.35018,
      "duration": 20
    },
    {
      "address": "3501 Fremont Ave N, Seattle, WA 98103",
      "lat": 47.6508,
      "lng": -122.3499,
      "duration": 15
    },
    {
      "address": "5300 Ballard Ave NW, Seattle, WA 98107",
      "lat": 47.66648,
      "lng": -122.3833,
      "duration": 10
    },
    {
      "address": "2200 NW Market St, Seattle, WA 98107",
      "lat": 47.66867,
      "lng": -122.38491,
      "duration": 10
    },
    {
      "address": "5449 Ballard Ave NW, Seattle, WA 98107",
      "lat": 47.66825,
      "lng": -122.3866,
      "duration": 15
    },
    {
      "address": "4810 E Green Lake Way N, Seattle, WA 98105",
      "lat": 47.66383,
      "lng": -122.34269,
      "duration": 10
    },
    {
      "address": "7201 East Green Lake Dr N, Seattle, WA 98115",
      "lat": 47.68041,
      "lng": -122.32587,
      "duration": 10
    },
    {
      "address": "6800 E Green Lake Way N, Seattle, WA 98115",
      "lat": 47.67834,
      "lng": -122.32779,
      "duration": 20
    },
    {
      "address": "3801 Beacon Ave S, Seattle, WA 98108",
      "lat": 47.56984,
      "lng": -122.30775,
      "duration": 10
    },
    {
      "address": "4850 Rainier Ave S, Seattle, WA 98118",
      "lat": 47.55847,
      "lng": -122.28537,
      "duration": 10
    },
    {
      "address": "5600 Rainier Ave S, Seattle, WA 98118",
      "lat": 47.5517,
      "lng": -122.27798,
      "duration": 15
    },
    {
      "address": "4500 8th Ave NE, Seattle, WA 98105",
      "lat": 47.66146,
      "lng": -122.31957,
      "duration": 10
    },
    {
      "address": "6500 Roosevelt Way NE, Seattle, WA 98115",
      "lat": 47.67607,
      "lng": -122.31739,
      "duration": 10
    },
    {
      "address": "7500 35th Ave NE, Seattle, WA 98115",
      "lat": 47.68316,
      "lng": -122.2905,
      "duration": 15
    },
    {
      "address": "2801 Alaskan Way, Seattle, WA 98121",
      "lat": 47.61502,
      "lng": -122.35485,
      "duration": 20
    },
    {
      "address": "2200 Westlake Ave, Seattle, WA 98121",
      "lat": 47.61805,
      "lng": -122.33752,
      "duration": 10
    },
    {
      "address": "600 Pine St, Seattle, WA 98101",
      "lat": 47.61225,
      "lng": -122.33504,
      "duration": 15
    },
    {
      "address": "401 Pine St, Seattle, WA 98101",
      "lat": 47.61135,
      "lng": -122.33724,
      "duration": 10
    },
    {
      "address": "1401 Broadway, Seattle, WA 98122",
      "lat": 47.61385,
      "lng": -122.32081,
      "duration": 10
    },
    {
      "address": "1701 Broadway, Seattle, WA 98122",
      "lat": 47.6169,
      "lng": -122.32083,
      "duration": 15
    },
    {
      "address": "4221 University Way NE, Seattle, WA 98105",
      "lat": 47.65909,
      "lng": -122.31363,
      "duration": 10
    },
    {
      "address": "500 Broadway E, Seattle, WA 98102",
      "lat": 47.62337,
      "lng": -122.32095,
      "duration": 20
    },
    {
      "address": "600 Broadway E, Seattle, WA 98102",
      "lat": 47.62444,
      "lng": -122.3206,
      "duration": 15
    },
    {
      "address": "2300 East Madison St, Seattle, WA 98112",
      "lat": 47.61947,
      "lng": -122.30211,
      "duration": 10
    },
    {
      "address": "2400 East Madison St, Seattle, WA 98112",
      "lat": 47.62048,
      "lng": -122.30063,
      "duration": 10
    },
    {
      "address": "3010 East Madison St, Seattle, WA 98112",
      "lat": 47.62492,
      "lng": -122.29411,
      "duration": 15
    },
    {
      "address": "3500 Rainier Ave S, Seattle, WA 98144",
      "lat": 47.57156,
      "lng": -122.29302,
      "duration": 10
    },
    {
      "address": "3800 Rainier Ave S, Seattle, WA 98144",
      "lat": 47.56942,
      "lng": -122.29034,
      "duration": 10
    },
    {
      "address": "4100 Rainier Ave S, Seattle, WA 98144",
      "lat": 47.56589,
      "lng": -122.28868,
      "duration": 20
    },
    {
      "address": "1000 4th Ave, Seattle, WA 98164",
      "lat": 47.60636,
      "lng": -122.33317,
      "duration": 10
    },
    {
      "address": "1100 4th Ave, Seattle, WA 98101",
      "lat": 47.60719,
      "lng": -122.33315,
      "duration": 10
    },
    {
      "address": "1200 4th Ave, Seattle, WA 98101",
      "lat": 47.60775,
      "lng": -122.33449,
      "duration": 15
    },
    {
      "address": "2100 6th Ave, Seattle, WA 98121",
      "lat": 47.61527,
      "lng": -122.33987,
      "duration": 10
    },
    {
      "address": "2200 6th Ave, Seattle, WA 98121",
      "lat": 47.6162,
      "lng": -122.34137,
      "duration": 10
    },
    {
      "address": "2300 6th Ave, Seattle, WA 98121",
      "lat": 47.61681,
      "lng": -122.34241,
      "duration": 15
    },
    {
      "address": "3200 15th Ave W, Seattle, WA 98119",
      "lat": 47.64867,
      "lng": -122.37615,
      "duration": 20
    }
  ],
  "los-angeles": [
    {
      "address": "200 N Spring St, Los Angeles, CA 90012",
      "lat": 34.0539,
      "lng": -118.24355,
      "duration": 0
    },
    {
      "address": "800 W Olympic Blvd, Los Angeles, CA 90015",
      "lat": 34.04469,
      "lng": -118.26425,
      "duration": 10
    },
    {
      "address": "1000 S Figueroa St, Los Angeles, CA 90015",
      "lat": 34.0448,
      "lng": -118.26415,
      "duration": 10
    },
    {
      "address": "1111 S Figueroa St, Los Angeles, CA 90015",
      "lat": 34.04331,
      "lng": -118.26556,
      "duration": 15
    },
    {
      "address": "700 W 7th St, Los Angeles, CA 90017",
      "lat": 34.04816,
      "lng": -118.25793,
      "duration": 10
    },
    {
      "address": "800 W 7th St, Los Angeles, CA 90017",
      "lat": 34.04878,
      "lng": -118.25891,
      "duration": 10
    },
    {
      "address": "900 W 7th St, Los Angeles, CA 90017",
      "lat": 34.04947,
      "lng": -118.26006,
      "duration": 15
    },
    {
      "address": "630 W 6th St, Los Angeles, CA 90017",
      "lat": 34.04912,
      "lng": -118.25586,
      "duration": 20
    },
    {
      "address": "730 W 6th St, Los Angeles, CA 90017",
      "lat": 34.04994,
      "lng": -118.25713,
      "duration": 10
    },
    {
      "address": "830 W 6th St, Los Angeles, CA 90017",
      "lat": 34.05067,
      "lng": -118.2583,
      "duration": 15
    },
    {
      "address": "1800 N Highland Ave, Los Angeles, CA 90028",
      "lat": 34.10448,
      "lng": -118.33776,
      "duration": 10
    },
    {
      "address": "1900 N Highland Ave, Los Angeles, CA 90028",
      "lat": 34.10549,
      "lng": -118.33728,
      "duration": 10
    },
    {
      "address": "2000 N Highland Ave, Los Angeles, CA 90028",
      "lat": 34.10696,
      "lng": -118.33724,
      "duration": 15
    },
    {
      "address": "6801 Hollywood Blvd, Los Angeles, CA 90028",
      "lat": 34.10193,
      "lng": -118.33962,
      "duration": 10
    },
    {
      "address": "6901 Hollywood Blvd, Los Angeles, CA 90028",
      "lat": 34.10155,
      "lng": -118.34033,
      "duration": 20
    },
    {
      "address": "7001 Hollywood Blvd, Los Angeles, CA 90028",
      "lat": 34.10154,
      "lng": -118.34207,
      "duration": 15
    },
    {
      "address": "10250 Santa Monica Blvd, Los Angeles, CA 90067",
      "lat": 34.05752,
      "lng": -118.41759,
      "duration": 10
    },
    {
      "address": "10350 Santa Monica Blvd, Los Angeles, CA 90067",
      "lat": 34.05807,
      "lng": -118.42282,
      "duration": 10
    },
    {
      "address": "10450 Santa Monica Blvd, Los Angeles, CA 90067",
      "lat": 34.05652,
      "lng": -118.42504,
      "duration": 15
    },
    {
      "address": "10899 Wilshire Blvd, Los Angeles, CA 90024",
      "lat": 34.05887,
      "lng": -118.44358,
      "duration": 10
    },
    {
      "address": "10999 Wilshire Blvd, Los Angeles, CA 90024",
      "lat": 34.05778,
      "lng": -118.44767,
      "duration": 10
    },
    {
      "address": "11099 Wilshire Blvd, Los Angeles, CA 90024",
      "lat": 34.05715,
      "lng": -118.44979,
      "duration": 20
    },
    {
      "address": "3400 W 3rd St, Los Angeles, CA 90020",
      "lat": 34.06873,
      "lng": -118.28914,
      "duration": 10
    },
    {
      "address": "3500 W 3rd St, Los Angeles, CA 90020",
      "lat": 34.06905,
      "lng": -118.29181,
      "duration": 10
    },
    {
      "address": "3600 W 3rd St, Los Angeles, CA 90020",
      "lat": 34.06905,
      "lng": -118.29452,
      "duration": 15
    },
    {
      "address": "4300 Sunset Blvd, Los Angeles, CA 90027",
      "lat": 34.09459,
      "lng": -118.28314,
      "duration": 10
    },
    {
      "address": "4400 Sunset Blvd, Los Angeles, CA 90027",
      "lat": 34.09684,
      "lng": -118.2853,
      "duration": 10
    },
    {
      "address": "4500 Sunset Blvd, Los Angeles, CA 90027",
      "lat": 34.09813,
      "lng": -118.28757,
      "duration": 15
    },
    {
      "address": "4700 Melrose Ave, Los Angeles, CA 90029",
      "lat": 34.08354,
      "lng": -118.30262,
      "duration": 20
    },
    {
      "address": "4800 Melrose Ave, Los Angeles, CA 90029",
      "lat": 34.08354,
      "lng": -118.30493,
      "duration": 10
    },
    {
      "address": "4900 Melrose Ave, Los Angeles, CA 90029",
      "lat": 34.08352,
      "lng": -118.30713,
      "duration": 15
    },
    {
      "address": "1200 S Figueroa St, Los Angeles, CA 90015",
      "lat": 34.04172,
      "lng": -118.26704,
      "duration": 10
    },
    {
      "address": "1300 S Figueroa St, Los Angeles, CA 90015",
      "lat": 34.04027,
      "lng": -118.26828,
      "duration": 10
    },
    {
      "address": "1400 S Figueroa St, Los Angeles, CA 90015",
      "lat": 34.03882,
      "lng": -118.26919,
      "duration": 15
    },
    {
      "address": "2500 E 1st St, Los Angeles, CA 90033",
      "lat": 34.0431,
      "lng": -118.20838,
      "duration": 10
    },
    {
      "address": "2600 E 1st St, Los Angeles, CA 90033",
      "lat": 34.04254,
      "lng": -118.20713,
      "duration": 20
    },
    {
      "address": "2700 E 1st St, Los Angeles, CA 90033",
      "lat": 34.04159,
      "lng": -118.20581,
      "duration": 15
    },
    {
      "address": "3700 E Cesar E Chavez Ave, Los Angeles, CA 90063",
      "lat": 34.04052,
      "lng": -118.18568,
      "duration": 10
    },
    {
      "address": "3800 E Cesar E Chavez Ave, Los Angeles, CA 90063",
      "lat": 34.04052,
      "lng": -118.18451,
      "duration": 10
    },
    {
      "address": "3900 E Cesar E Chavez Ave, Los Angeles, CA 90063",
      "lat": 34.04054,
      "lng": -118.18215,
      "duration": 15
    },
    {
      "address": "5000 W Pico Blvd, Los Angeles, CA 90019",
      "lat": 34.04777,
      "lng": -118.34612,
      "duration": 10
    },
    {
      "address": "5100 W Pico Blvd, Los Angeles, CA 90019",
      "lat": 34.04785,
      "lng": -118.34964,
      "duration": 10
    },
    {
      "address": "5200 W Pico Blvd, Los Angeles, CA 90019",
      "lat": 34.04818,
      "lng": -118.35181,
      "duration": 20
    },
    {
      "address": "6000 W Sunset Blvd, Los Angeles, CA 90028",
      "lat": 34.09802,
      "lng": -118.32026,
      "duration": 10
    },
    {
      "address": "6100 W Sunset Blvd, Los Angeles, CA 90028",
      "lat": 34.09801,
      "lng": -118.32257,
      "duration": 10
    },
    {
      "address": "6200 W Sunset Blvd, Los Angeles, CA 90028",
      "lat": 34.09801,
      "lng": -118.32392,
      "duration": 15
    },
    {
      "address": "1500 S La Brea Ave, Los Angeles, CA 90019",
      "lat": 34.0466,
      "lng": -118.34515,
      "duration": 10
    },
    {
      "address": "1600 S La Brea Ave, Los Angeles, CA 90019",
      "lat": 34.04568,
      "lng": -118.34551,
      "duration": 10
    },
    {
      "address": "1700 S La Brea Ave, Los Angeles, CA 90019",
      "lat": 34.044,
      "lng": -118.34611,
      "duration": 15
    },
    {
      "address": "2200 E Colorado Blvd, Pasadena, CA 91107",
      "lat": 34.14607,
      "lng": -118.10515,
      "duration": 20
    }
  ],
  "new-york": [
    {
      "address": "350 5th Ave, New York, NY 10118",
      "lat": 40.74812,
      "lng": -73.9848,
      "duration": 0
    },
    {
      "address": "1 Times Sq, New York, NY 10036",
      "lat": 40.75629,
      "lng": -73.98671,
      "duration": 10
    },
    {
      "address": "11 Times Sq, New York, NY 10036",
      "lat": 40.75686,
      "lng": -73.99007,
      "duration": 10
    },
    {
      "address": "20 Times Sq, New York, NY 10036",
      "lat": 40.7556,
      "lng": -73.98646,
      "duration": 15
    },
    {
      "address": "1560 Broadway, New York, NY 10036",
      "lat": 40.75881,
      "lng": -73.98487,
      "duration": 10
    },
    {
      "address": "1570 Broadway, New York, NY 10036",
      "lat": 40.75908,
      "lng": -73.98468,
      "duration": 10
    },
    {
      "address": "1580 Broadway, New York, NY 10036",
      "lat": 40.75962,
      "lng": -73.98502,
      "duration": 15
    },
    {
      "address": "200 Central Park West, New York, NY 10024",
      "lat": 40.78117,
      "lng": -73.97233,
      "duration": 20
    },
    {
      "address": "210 Central Park West, New York, NY 10024",
      "lat": 40.78191,
      "lng": -73.9718,
      "duration": 10
    },
    {
      "address": "220 Central Park West, New York, NY 10024",
      "lat": 40.78246,
      "lng": -73.97141,
      "duration": 15
    },
    {
      "address": "1 Penn Plaza, New York, NY 10119",
      "lat": 40.75063,
      "lng": -73.99183,
      "duration": 10
    },
    {
      "address": "2 Penn Plaza, New York, NY 10121",
      "lat": 40.75111,
      "lng": -73.99296,
      "duration": 10
    },
    {
      "address": "11 Penn Plaza, New York, NY 10001",
      "lat": 40.74936,
      "lng": -73.99178,
      "duration": 15
    },
    {
      "address": "4 Pennsylvania Plaza, New York, NY 10001",
      "lat": 40.75058,
      "lng": -73.99224,
      "duration": 10
    },
    {
      "address": "5 Pennsylvania Plaza, New York, NY 10001",
      "lat": 40.75059,
      "lng": -73.99223,
      "duration": 20
    },
    {
      "address": "6 Pennsylvania Plaza, New York, NY 10001",
      "lat": 40.75052,
      "lng": -73.99228,
      "duration": 15
    },
    {
      "address": "100 Wall St, New York, NY 10005",
      "lat": 40.70507,
      "lng": -74.00725,
      "duration": 10
    },
    {
      "address": "110 Wall St, New York, NY 10005",
      "lat": 40.70505,
      "lng": -74.00659,
      "duration": 10
    },
    {
      "address": "120 Wall St, New York, NY 10005",
      "lat": 40.70442,
      "lng": -74.00636,
      "duration": 15
    },
    {
      "address": "200 Park Ave, New York, NY 10166",
      "lat": 40.75372,
      "lng": -73.9772,
      "duration": 10
    },
    {
      "address": "210 Park Ave, New York, NY 10166",
      "lat": 40.75336,
      "lng": -73.97747,
      "duration": 10
    },
    {
      "address": "220 Park Ave, New York, NY 10166",
      "lat": 40.75392,
      "lng": -73.97705,
      "duration": 20
    },
    {
      "address": "350 Madison Ave, New York, NY 10017",
      "lat": 40.75454,
      "lng": -73.97801,
      "duration": 10
    },
    {
      "address": "360 Madison Ave, New York, NY 10017",
      "lat": 40.75473,
      "lng": -73.97787,
      "duration": 10
    },
    {
      "address": "370 Madison Ave, New York, NY 10017",
      "lat": 40.75522,
      "lng": -73.97751,
      "duration": 15
    },
    {
      "address": "450 Lexington Ave, New York, NY 10017",
      "lat": 40.75303,
      "lng": -73.97489,
      "duration": 10
    },
    {
      "address": "460 Lexington Ave, New York, NY 10017",
      "lat": 40.75367,
      "lng": -73.97442,
      "duration": 10
    },
    {
      "address": "470 Lexington Ave, New York, NY 10017",
      "lat": 40.75378,
      "lng": -73.97434,
      "duration": 15
    },
    {
      "address": "1 World Trade Center, New York, NY 10007",
      "lat": 40.71279,
      "lng": -74.01348,
      "duration": 20
    },
    {
      "address": "3 World Trade Center, New York, NY 10007",
      "lat": 40.70968,
      "lng": -74.01166,
      "duration": 10
    },
    {
      "address": "4 World Trade Center, New York, NY 10007",
      "lat": 40.70993,
      "lng": -74.01221,
      "duration": 15
    },
    {
      "address": "75 9th Ave, New York, NY 10011",
      "lat": 40.74217,
      "lng": -74.00611,
      "duration": 10
    },
    {
      "address": "85 9th Ave, New York, NY 10011",
      "lat": 40.74249,
      "lng": -74.00426,
      "duration": 10
    },
    {
      "address": "95 9th Ave, New York, NY 10011",
      "lat": 40.74259,
      "lng": -74.00419,
      "duration": 15
    },
    {
      "address": "200 Varick St, New York, NY 10014",
      "lat": 40.72803,
      "lng": -74.00544,
      "duration": 10
    },
    {
      "address": "210 Varick St, New York, NY 10014",
      "lat": 40.72898,
      "lng": -74.00527,
      "duration": 20
    },
    {
      "address": "220 Varick St, New York, NY 10014",
      "lat": 40.72903,
      "lng": -74.00526,
      "duration": 15
    },
    {
      "address": "1000 3rd Ave, New York, NY 10022",
      "lat": 40.76186,
      "lng": -73.96636,
      "duration": 10
    },
    {
      "address": "1010 3rd Ave, New York, NY 10022",
      "lat": 40.76237,
      "lng": -73.96598,
      "duration": 10
    },
    {
      "address": "1020 3rd Ave, New York, NY 10022",
      "lat": 40.7625,
      "lng": -73.96588,
      "duration": 15
    },
    {
      "address": "500 Grand St, New York, NY 10002",
      "lat": 40.71483,
      "lng": -73.98298,
      "duration": 10
    },
    {
      "address": "510 Grand St, New York, NY 10002",
      "lat": 40.71453,
      "lng": -73.98188,
      "duration": 10
    },
    {
      "address": "520 Grand St, New York, NY 10002",
      "lat": 40.71451,
      "lng": -73.98182,
      "duration": 20
    },
    {
      "address": "1 Rockefeller Plaza, New York, NY 10020",
      "lat": 40.75816,
      "lng": -73.97919,
      "duration": 10
    },
    {
      "address": "10 Rockefeller Plaza, New York, NY 10020",
      "lat": 40.75825,
      "lng": -73.97912,
      "duration": 10
    },
    {
      "address": "30 Rockefeller Plaza, New York, NY 10112",
      "lat": 40.75879,
      "lng": -73.97869,
      "duration": 15
    },
    {
      "address": "233 Broadway, New York, NY 10279",
      "lat": 40.7124,
      "lng": -74.00777,
      "duration": 10
    },
    {
      "address": "243 Broadway, New York, NY 10279",
      "lat": 40.77829,
      "lng": -73.98187,
      "duration": 10
    },
    {
      "address": "253 Broadway, New York, NY 10279",
      "lat": 40.71321,
      "lng": -74.00708,
      "duration": 15
    },
    {
      "address": "131 E 23rd St, New York, NY 10010",
      "lat": 40.73958,
      "lng": -73.98494,
      "duration": 20
    }
  ],
  "london": [
    {
      "address": "Westminster, London SW1A 0AA, UK",
      "lat": 51.50025,
      "lng": -0.12482,
      "duration": 0
    },
    {
      "address": "10 Downing St, London SW1A 2AA, UK",
      "lat": 51.50322,
      "lng": -0.12768,
      "duration": 10
    },
    {
      "address": "20 Deans Yd, London SW1P 3PA, UK",
      "lat": 51.49867,
      "lng": -0.12857,
      "duration": 10
    },
    {
      "address": "30 James St, London SW1A 2NP, UK",
      "lat": 51.51526,
      "lng": -0.15071,
      "duration": 15
    },
    {
      "address": "1 Canada Square, London E14 5AB, UK",
      "lat": 51.50525,
      "lng": -0.01908,
      "duration": 10
    },
    {
      "address": "5 Canada Square, London E14 5AQ, UK",
      "lat": 51.50519,
      "lng": -0.01865,
      "duration": 10
    },
    {
      "address": "10 Canada Square, London E14 5NR, UK",
      "lat": 51.50492,
      "lng": -0.01618,
      "duration": 15
    },
    {
      "address": "221B Baker St, London NW1 6XE, UK",
      "lat": 51.52375,
      "lng": -0.15828,
      "duration": 20
    },
    {
      "address": "230 Baker St, London NW1 6XE, UK",
      "lat": 51.5237,
      "lng": -0.15826,
      "duration": 10
    },
    {
      "address": "240 Baker St, London NW1 6XE, UK",
      "lat": 51.52385,
      "lng": -0.15833,
      "duration": 15
    },
    {
      "address": "The British Museum, Great Russell St, London WC1B 3DG, UK",
      "lat": 51.51812,
      "lng": -0.12642,
      "duration": 10
    },
    {
      "address": "50 Russell Square, London WC1B 4JP, UK",
      "lat": 51.52091,
      "lng": -0.12547,
      "duration": 10
    },
    {
      "address": "60 Russell Square, London WC1B 4JP, UK",
      "lat": 51.52143,
      "lng": -0.12427,
      "duration": 15
    },
    {
      "address": "Tower Bridge Rd, London SE1 2UP, UK",
      "lat": 51.50358,
      "lng": -0.07666,
      "duration": 10
    },
    {
      "address": "2 Tower Bridge Rd, London SE1 2UP, UK",
      "lat": 51.49909,
      "lng": -0.07911,
      "duration": 20
    },
    {
      "address": "3 Tower Bridge Rd, London SE1 2UP, UK",
      "lat": 51.49701,
      "lng": -0.08108,
      "duration": 15
    },
    {
      "address": "1 Leicester Square, London WC2H 7NA, UK",
      "lat": 51.51064,
      "lng": -0.13062,
      "duration": 10
    },
    {
      "address": "2 Leicester Square, London WC2H 7NA, UK",
      "lat": 51.51068,
      "lng": -0.1305,
      "duration": 10
    },
    {
      "address": "3 Leicester Square, London WC2H 7NA, UK",
      "lat": 51.51066,
      "lng": -0.13055,
      "duration": 15
    },
    {
      "address": "100 Oxford St, London W1D 1LL, UK",
      "lat": 51.51599,
      "lng": -0.13528,
      "duration": 10
    },
    {
      "address": "200 Oxford St, London W1D 1LL, UK",
      "lat": 51.51549,
      "lng": -0.14025,
      "duration": 10
    },
    {
      "address": "300 Oxford St, London W1D 1LL, UK",
      "lat": 51.51491,
      "lng": -0.14487,
      "duration": 20
    },
    {
      "address": "1 Piccadilly, London W1J 0DA, UK",
      "lat": 51.50856,
      "lng": -0.1384,
      "duration": 10
    },
    {
      "address": "10 Piccadilly, London W1J 0DA, UK",
      "lat": 51.50951,
      "lng": -0.13545,
      "duration": 10
    },
    {
      "address": "20 Piccadilly, London W1J 0DA, UK",
      "lat": 51.50933,
      "lng": -0.13599,
      "duration": 15
    },
    {
      "address": "1 Kensington Gore, London SW7 2AR, UK",
      "lat": 51.50121,
      "lng": -0.17569,
      "duration": 10
    },
    {
      "address": "2 Kensington Gore, London SW7 2AR, UK",
      "lat": 51.50121,
      "lng": -0.17674,
      "duration": 10
    },
    {
      "address": "1 Camden High St, London NW1 7JE, UK",
      "lat": 51.53463,
      "lng": -0.13904,
      "duration": 15
    },
    {
      "address": "10 Camden High St, London NW1 7JE, UK",
      "lat": 51.53486,
      "lng": -0.13901,
      "duration": 20
    },
    {
      "address": "20 Camden High St, London NW1 7JE, UK",
      "lat": 51.5352,
      "lng": -0.13911,
      "duration": 10
    },
    {
      "address": "1 Brick Lane, London E1 6SB, UK",
      "lat": 51.52428,
      "lng": -0.07158,
      "duration": 15
    },
    {
      "address": "10 Brick Lane, London E1 6SB, UK",
      "lat": 51.52159,
      "lng": -0.07176,
      "duration": 10
    },
    {
      "address": "20 Brick Lane, London E1 6SB, UK",
      "lat": 51.51802,
      "lng": -0.07115,
      "duration": 10
    },
    {
      "address": "1 Shoreditch High St, London E1 6JJ, UK",
      "lat": 51.52161,
      "lng": -0.07842,
      "duration": 15
    },
    {
      "address": "10 Shoreditch High St, London E1 6JJ, UK",
      "lat": 51.52177,
      "lng": -0.07831,
      "duration": 10
    },
    {
      "address": "20 Shoreditch High St, London E1 6JJ, UK",
      "lat": 51.52228,
      "lng": -0.07799,
      "duration": 20
    },
    {
      "address": "1 Strand, London WC2N 5EH, UK",
      "lat": 51.50785,
      "lng": -0.12678,
      "duration": 15
    },
    {
      "address": "10 Strand, London WC2N 5EH, UK",
      "lat": 51.50826,
      "lng": -0.12599,
      "duration": 10
    },
    {
      "address": "20 Strand, London WC2N 5EH, UK",
      "lat": 51.50892,
      "lng": -0.12485,
      "duration": 10
    },
    {
      "address": "1 Fleet St, London EC4Y 1HT, UK",
      "lat": 51.51396,
      "lng": -0.1077,
      "duration": 15
    },
    {
      "address": "10 Fleet St, London EC4Y 1HT, UK",
      "lat": 51.51382,
      "lng": -0.11125,
      "duration": 10
    },
    {
      "address": "20 Fleet St, London EC4Y 1HT, UK",
      "lat": 51.51391,
      "lng": -0.1107,
      "duration": 10
    },
    {
      "address": "1 Borough High St, London SE1 1LB, UK",
      "lat": 51.50266,
      "lng": -0.09212,
      "duration": 20
    },
    {
      "address": "10 Borough High St, London SE1 1LB, UK",
      "lat": 51.50587,
      "lng": -0.08868,
      "duration": 10
    },
    {
      "address": "20 Borough High St, London SE1 1LB, UK",
      "lat": 51.50481,
      "lng": -0.09014,
      "duration": 10
    },
    {
      "address": "1 Liverpool St, London EC2M 7PY, UK",
      "lat": 51.51774,
      "lng": -0.08425,
      "duration": 15
    },
    {
      "address": "10 Liverpool St, London EC2M 7PY, UK",
      "lat": 51.51764,
      "lng": -0.08362,
      "duration": 10
    },
    {
      "address": "20 Liverpool St, London EC2M 7PY, UK",
      "lat": 51.51743,
      "lng": -0.08249,
      "duration": 10
    },
    {
      "address": "1 Kings Cross Rd, London N1 0AP, UK",
      "lat": 51.52647,
      "lng": -0.11313,
      "duration": 15
    },
    {
      "address": "10 Kings Cross Rd, London N1 0AP, UK",
      "lat": 51.52703,
      "lng": -0.11439,
      "duration": 20
    }
  ],
  "paris": [
    {
      "address": "5 Av. Anatole France, 75007 Paris, France",
      "lat": 48.85765,
      "lng": 2.29591,
      "duration": 0
    },
    {
      "address": "1 Av. des Champs-Élysées, 75008 Paris, France",
      "lat": 48.86665,
      "lng": 2.31748,
      "duration": 10
    },
    {
      "address": "20 Av. des Champs-Élysées, 75008 Paris, France",
      "lat": 48.86932,
      "lng": 2.30905,
      "duration": 10
    },
    {
      "address": "1 Rue de Rivoli, 75001 Paris, France",
      "lat": 48.85562,
      "lng": 2.35932,
      "duration": 15
    },
    {
      "address": "10 Rue de Rivoli, 75001 Paris, France",
      "lat": 48.85538,
      "lng": 2.36032,
      "duration": 10
    },
    {
      "address": "20 Rue de Rivoli, 75001 Paris, France",
      "lat": 48.85576,
      "lng": 2.35873,
      "duration": 10
    },
    {
      "address": "1 Place de la Bastille, 75011 Paris, France",
      "lat": 48.85348,
      "lng": 2.36962,
      "duration": 15
    },
    {
      "address": "2 Place de la Bastille, 75011 Paris, France",
      "lat": 48.85322,
      "lng": 2.37028,
      "duration": 20
    },
    {
      "address": "3 Place de la Bastille, 75011 Paris, France",
      "lat": 48.85311,
      "lng": 2.36847,
      "duration": 10
    },
    {
      "address": "1 Rue de la Paix, 75002 Paris, France",
      "lat": 48.86849,
      "lng": 2.33044,
      "duration": 15
    },
    {
      "address": "10 Rue de la Paix, 75002 Paris, France",
      "lat": 48.86904,
      "lng": 2.33099,
      "duration": 10
    },
    {
      "address": "20 Rue de la Paix, 75002 Paris, France",
      "lat": 48.86975,
      "lng": 2.3317,
      "duration": 10
    },
    {
      "address": "1 Boulevard Haussmann, 75009 Paris, France",
      "lat": 48.87221,
      "lng": 2.33841,
      "duration": 15
    },
    {
      "address": "10 Boulevard Haussmann, 75009 Paris, France",
      "lat": 48.87226,
      "lng": 2.33809,
      "duration": 10
    },
    {
      "address": "20 Boulevard Haussmann, 75009 Paris, France",
      "lat": 48.87251,
      "lng": 2.33632,
      "duration": 20
    },
    {
      "address": "1 Rue de Vaugirard, 75006 Paris, France",
      "lat": 48.84887,
      "lng": 2.34127,
      "duration": 15
    },
    {
      "address": "10 Rue de Vaugirard, 75006 Paris, France",
      "lat": 48.849,
      "lng": 2.3397,
      "duration": 10
    },
    {
      "address": "20 Rue de Vaugirard, 75006 Paris, France",
      "lat": 48.84923,
      "lng": 2.33818,
      "duration": 10
    },
    {
      "address": "1 Rue Mouffetard, 75005 Paris, France",
      "lat": 48.84495,
      "lng": 2.34915,
      "duration": 15
    },
    {
      "address": "10 Rue Mouffetard, 75005 Paris, France",
      "lat": 48.84459,
      "lng": 2.34922,
      "duration": 10
    },
    {
      "address": "20 Rue Mouffetard, 75005 Paris, France",
      "lat": 48.84431,
      "lng": 2.34929,
      "duration": 10
    },
    {
      "address": "1 Rue de Charonne, 75011 Paris, France",
      "lat": 48.85199,
      "lng": 2.37392,
      "duration": 20
    },
    {
      "address": "10 Rue de Charonne, 75011 Paris, France",
      "lat": 48.85236,
      "lng": 2.37418,
      "duration": 10
    },
    {
      "address": "20 Rue de Charonne, 75011 Paris, France",
      "lat": 48.85305,
      "lng": 2.37472,
      "duration": 10
    },
    {
      "address": "1 Rue Oberkampf, 75011 Paris, France",
      "lat": 48.86274,
      "lng": 2.3675,
      "duration": 15
    },
    {
      "address": "10 Rue Oberkampf, 75011 Paris, France",
      "lat": 48.8631,
      "lng": 2.36845,
      "duration": 10
    },
    {
      "address": "20 Rue Oberkampf, 75011 Paris, France",
      "lat": 48.86349,
      "lng": 2.36947,
      "duration": 10
    },
    {
      "address": "1 Rue de la Roquette, 75011 Paris, France",
      "lat": 48.85367,
      "lng": 2.3707,
      "duration": 15
    },
    {
      "address": "10 Rue de la Roquette, 75011 Paris, France",
      "lat": 48.85355,
      "lng": 2.37058,
      "duration": 20
    },
    {
      "address": "20 Rue de la Roquette, 75011 Paris, France",
      "lat": 48.854,
      "lng": 2.37103,
      "duration": 10
    },
    {
      "address": "1 Rue du Faubourg Saint-Antoine, 75011 Paris, France",
      "lat": 48.85317,
      "lng": 2.37047,
      "duration": 15
    },
    {
      "address": "10 Rue du Faubourg Saint-Antoine, 75011 Paris, France",
      "lat": 48.85288,
      "lng": 2.37092,
      "duration": 10
    },
    {
      "address": "20 Rue du Faubourg Saint-Antoine, 75011 Paris, France",
      "lat": 48.85272,
      "lng": 2.37121,
      "duration": 10
    },
    {
      "address": "1 Rue de Belleville, 75020 Paris, France",
      "lat": 48.87217,
      "lng": 2.37723,
      "duration": 15
    },
    {
      "address": "10 Rue de Belleville, 75020 Paris, France",
      "lat": 48.87246,
      "lng": 2.37828,
      "duration": 10
    },
    {
      "address": "20 Rue de Belleville, 75020 Paris, France",
      "lat": 48.87263,
      "lng": 2.37898,
      "duration": 20
    },
    {
      "address": "1 Rue de la Pompe, 75016 Paris, France",
      "lat": 48.8585,
      "lng": 2.27495,
      "duration": 15
    },
    {
      "address": "10 Rue de la Pompe, 75016 Paris, France",
      "lat": 48.8594,
      "lng": 2.27515,
      "duration": 10
    },
    {
      "address": "20 Rue de la Pompe, 75016 Paris, France",
      "lat": 48.86023,
      "lng": 2.27507,
      "duration": 10
    },
    {
      "address": "1 Rue de Passy, 75016 Paris, France",
      "lat": 48.85845,
      "lng": 2.28416,
      "duration": 15
    },
    {
      "address": "10 Rue de Passy, 75016 Paris, France",
      "lat": 48.85834,
      "lng": 2.28347,
      "duration": 10
    },
    {
      "address": "20 Rue de Passy, 75016 Paris, France",
      "lat": 48.85813,
      "lng": 2.28207,
      "duration": 10
    },
    {
      "address": "1 Rue de Tolbiac, 75013 Paris, France",
      "lat": 48.83035,
      "lng": 2.37632,
      "duration": 20
    },
    {
      "address": "10 Rue de Tolbiac, 75013 Paris, France",
      "lat": 48.82979,
      "lng": 2.37528,
      "duration": 10
    },
    {
      "address": "20 Rue de Tolbiac, 75013 Paris, France",
      "lat": 48.8292,
      "lng": 2.37425,
      "duration": 10
    },
    {
      "address": "1 Rue de la Gare, 75013 Paris, France",
      "lat": 48.83264,
      "lng": 2.37969,
      "duration": 15
    },
    {
      "address": "10 Rue de la Gare, 75013 Paris, France",
      "lat": 48.90172,
      "lng": 2.37245,
      "duration": 10
    },
    {
      "address": "1 Rue du Commerce, 75015 Paris, France",
      "lat": 48.84895,
      "lng": 2.29776,
      "duration": 10
    },
    {
      "address": "10 Rue du Commerce, 75015 Paris, France",
      "lat": 48.84837,
      "lng": 2.2971,
      "duration": 15
    },
    {
      "address": "20 Rue du Commerce, 75015 Paris, France",
      "lat": 48.84797,
      "lng": 2.2967,
      "duration": 20
    }
  ],
  "berlin": [
    {
      "address": "Pariser Platz, 10117 Berlin, Germany",
      "lat": 52.5163,
      "lng": 13.37999,
      "duration": 0
    },
    {
      "address": "Unter den Linden 1, 10117 Berlin, Germany",
      "lat": 52.51758,
      "lng": 13.39778,
      "duration": 10
    },
    {
      "address": "Unter den Linden 10, 10117 Berlin, Germany",
      "lat": 52.51724,
      "lng": 13.39038,
      "duration": 10
    },
    {
      "address": "Unter den Linden 20, 10117 Berlin, Germany",
      "lat": 52.51717,
      "lng": 13.38924,
      "duration": 15
    },
    {
      "address": "Friedrichstraße 1, 10117 Berlin, Germany",
      "lat": 52.50015,
      "lng": 13.39157,
      "duration": 10
    },
    {
      "address": "Friedrichstraße 10, 10117 Berlin, Germany",
      "lat": 52.50121,
      "lng": 13.3914,
      "duration": 10
    },
    {
      "address": "Friedrichstraße 20, 10117 Berlin, Germany",
      "lat": 52.50306,
      "lng": 13.39112,
      "duration": 15
    },
    {
      "address": "Karl-Marx-Allee 1, 10178 Berlin, Germany",
      "lat": 52.52175,
      "lng": 13.41769,
      "duration": 20
    },
    {
      "address": "Karl-Marx-Allee 10, 10178 Berlin, Germany",
      "lat": 52.52131,
      "lng": 13.41851,
      "duration": 10
    },
    {
      "address": "Karl-Marx-Allee 20, 10178 Berlin, Germany",
      "lat": 52.52081,
      "lng": 13.42014,
      "duration": 15
    },
    {
      "address": "Alexanderplatz 1, 10178 Berlin, Germany",
      "lat": 52.52115,
      "lng": 13.4129,
      "duration": 10
    },
    {
      "address": "Alexanderplatz 2, 10178 Berlin, Germany",
      "lat": 52.52101,
      "lng": 13.41339,
      "duration": 10
    },
    {
      "address": "Alexanderplatz 3, 10178 Berlin, Germany",
      "lat": 52.52178,
      "lng": 13.41405,
      "duration": 15
    },
    {
      "address": "Potsdamer Platz 1, 10785 Berlin, Germany",
      "lat": 52.50933,
      "lng": 13.37548,
      "duration": 10
    },
    {
      "address": "Potsdamer Platz 2, 10785 Berlin, Germany",
      "lat": 52.5095,
      "lng": 13.37533,
      "duration": 20
    },
    {
      "address": "Potsdamer Platz 3, 10785 Berlin, Germany",
      "lat": 52.51004,
      "lng": 13.37537,
      "duration": 15
    },
    {
      "address": "Kurfürstendamm 1, 10719 Berlin, Germany",
      "lat": 52.50163,
      "lng": 13.31728,
      "duration": 10
    },
    {
      "address": "Kurfürstendamm 10, 10719 Berlin, Germany",
      "lat": 52.50459,
      "lng": 13.33399,
      "duration": 10
    },
    {
      "address": "Kurfürstendamm 20, 10719 Berlin, Germany",
      "lat": 52.50371,
      "lng": 13.33066,
      "duration": 15
    },
    {
      "address": "Oranienburger Str. 1, 10178 Berlin, Germany",
      "lat": 52.52366,
      "lng": 13.40158,
      "duration": 10
    },
    {
      "address": "Oranienburger Str. 10, 10178 Berlin, Germany",
      "lat": 52.52368,
      "lng": 13.3998,
      "duration": 10
    },
    {
      "address": "Oranienburger Str. 20, 10178 Berlin, Germany",
      "lat": 52.52401,
      "lng": 13.39667,
      "duration": 20
    },
    {
      "address": "Torstraße 1, 10119 Berlin, Germany",
      "lat": 52.52736,
      "lng": 13.41529,
      "duration": 10
    },
    {
      "address": "Torstraße 10, 10119 Berlin, Germany",
      "lat": 52.52755,
      "lng": 13.4141,
      "duration": 10
    },
    {
      "address": "Torstraße 20, 10119 Berlin, Germany",
      "lat": 52.52778,
      "lng": 13.41339,
      "duration": 15
    },
    {
      "address": "Warschauer Str. 1, 10243 Berlin, Germany",
      "lat": 52.51493,
      "lng": 13.45346,
      "duration": 10
    },
    {
      "address": "Warschauer Str. 10, 10243 Berlin, Germany",
      "lat": 52.51352,
      "lng": 13.45283,
      "duration": 10
    },
    {
      "address": "Warschauer Str. 20, 10243 Berlin, Germany",
      "lat": 52.5116,
      "lng": 13.45197,
      "duration": 15
    },
    {
      "address": "Sonntagstraße 1, 10245 Berlin, Germany",
      "lat": 52.50453,
      "lng": 13.46782,
      "duration": 20
    },
    {
      "address": "Sonntagstraße 10, 10245 Berlin, Germany",
      "lat": 52.50587,
      "lng": 13.46614,
      "duration": 10
    },
    {
      "address": "Sonntagstraße 20, 10245 Berlin, Germany",
      "lat": 52.50749,
      "lng": 13.46418,
      "duration": 15
    },
    {
      "address": "Kottbusser Damm 1, 10999 Berlin, Germany",
      "lat": 52.49539,
      "lng": 13.42049,
      "duration": 10
    },
    {
      "address": "Kottbusser Damm 10, 10999 Berlin, Germany",
      "lat": 52.49372,
      "lng": 13.42155,
      "duration": 10
    },
    {
      "address": "Kottbusser Damm 20, 10999 Berlin, Germany",
      "lat": 52.49182,
      "lng": 13.42274,
      "duration": 15
    },
    {
      "address": "Schönhauser Allee 1, 10435 Berlin, Germany",
      "lat": 52.52889,
      "lng": 13.40989,
      "duration": 10
    },
    {
      "address": "Schönhauser Allee 10, 10435 Berlin, Germany",
      "lat": 52.53061,
      "lng": 13.4113,
      "duration": 20
    },
    {
      "address": "Schönhauser Allee 20, 10435 Berlin, Germany",
      "lat": 52.5332,
      "lng": 13.41297,
      "duration": 15
    },
    {
      "address": "Prenzlauer Allee 1, 10405 Berlin, Germany",
      "lat": 52.5273,
      "lng": 13.41617,
      "duration": 10
    },
    {
      "address": "Prenzlauer Allee 10, 10405 Berlin, Germany",
      "lat": 52.5301,
      "lng": 13.41875,
      "duration": 10
    },
    {
      "address": "Prenzlauer Allee 20, 10405 Berlin, Germany",
      "lat": 52.53137,
      "lng": 13.41973,
      "duration": 15
    },
    {
      "address": "Stargarder Str. 1, 10437 Berlin, Germany",
      "lat": 52.54761,
      "lng": 13.41386,
      "duration": 10
    },
    {
      "address": "Stargarder Str. 10, 10437 Berlin, Germany",
      "lat": 52.54706,
      "lng": 13.41668,
      "duration": 10
    },
    {
      "address": "Stargarder Str. 20, 10437 Berlin, Germany",
      "lat": 52.54565,
      "lng": 13.42023,
      "duration": 20
    },
    {
      "address": "Greifswalder Str. 1, 10405 Berlin, Germany",
      "lat": 52.52852,
      "lng": 13.42435,
      "duration": 10
    },
    {
      "address": "Greifswalder Str. 10, 10405 Berlin, Germany",
      "lat": 52.52978,
      "lng": 13.42578,
      "duration": 10
    },
    {
      "address": "Greifswalder Str. 20, 10405 Berlin, Germany",
      "lat": 52.53108,
      "lng": 13.42729,
      "duration": 15
    },
    {
      "address": "Boxhagener Str. 1, 10245 Berlin, Germany",
      "lat": 52.51408,
      "lng": 13.45382,
      "duration": 10
    },
    {
      "address": "Boxhagener Str. 10, 10245 Berlin, Germany",
      "lat": 52.51399,
      "lng": 13.45413,
      "duration": 10
    },
    {
      "address": "Boxhagener Str. 20, 10245 Berlin, Germany",
      "lat": 52.51333,
      "lng": 13.45616,
      "duration": 15
    },
    {
      "address": "Karl-Marx-Straße 1, 12043 Berlin, Germany",
      "lat": 52.48626,
      "lng": 13.42468,
      "duration": 20
    }
  ],
  "tokyo": [
    {
      "address": "3-38-1 Shinjuku, Shinjuku, Tokyo 160-0022, Japan",
      "lat": 35.69133,
      "lng": 139.70134,
      "duration": 0
    },
    {
      "address": "1-1-1 Shinjuku, Shinjuku, Tokyo 160-0022, Japan",
      "lat": 35.68739,
      "lng": 139.71359,
      "duration": 10
    },
    {
      "address": "2-1-2 Shinjuku, Shinjuku, Tokyo 160-0022, Japan",
      "lat": 35.6882,
      "lng": 139.70946,
      "duration": 10
    },
    {
      "address": "4-1-4 Shinjuku, Shinjuku, Tokyo 160-0022, Japan",
      "lat": 35.68831,
      "lng": 139.70255,
      "duration": 15
    },
    {
      "address": "2-2-2 Shibuya, Shibuya, Tokyo 150-0002, Japan",
      "lat": 35.66083,
      "lng": 139.70869,
      "duration": 10
    },
    {
      "address": "3-2-3 Shibuya, Shibuya, Tokyo 150-0002, Japan",
      "lat": 35.657,
      "lng": 139.70763,
      "duration": 10
    },
    {
      "address": "4-2-4 Shibuya, Shibuya, Tokyo 150-0002, Japan",
      "lat": 35.65993,
      "lng": 139.7128,
      "duration": 15
    },
    {
      "address": "5-2-5 Shibuya, Shibuya, Tokyo 150-0002, Japan",
      "lat": 35.65937,
      "lng": 139.7063,
      "duration": 20
    },
    {
      "address": "1-3-1 Asakusa, Taito, Tokyo 111-0032, Japan",
      "lat": 35.71088,
      "lng": 139.79642,
      "duration": 10
    },
    {
      "address": "2-3-2 Asakusa, Taito, Tokyo 111-0032, Japan",
      "lat": 35.71283,
      "lng": 139.79626,
      "duration": 15
    },
    {
      "address": "5-3-5 Asakusa, Taito, Tokyo 111-0032, Japan",
      "lat": 35.7195,
      "lng": 139.79827,
      "duration": 10
    },
    {
      "address": "2-4-2 Oshiage, Sumida, Tokyo 131-0045, Japan",
      "lat": 35.7112,
      "lng": 139.81037,
      "duration": 10
    },
    {
      "address": "3-4-3 Oshiage, Sumida, Tokyo 131-0045, Japan",
      "lat": 35.71335,
      "lng": 139.81678,
      "duration": 15
    },
    {
      "address": "4-4-4 Oshiage, Sumida, Tokyo 131-0045, Japan",
      "lat": 35.71176,
      "lng": 139.8155,
      "duration": 10
    },
    {
      "address": "5-5-5 Shiba-koen, Minato, Tokyo 105-0011, Japan",
      "lat": 35.65763,
      "lng": 139.74852,
      "duration": 20
    },
    {
      "address": "3-6-3 Koraku, Bunkyo, Tokyo 112-0004, Japan",
      "lat": 35.70485,
      "lng": 139.74927,
      "duration": 15
    },
    {
      "address": "1-7-1 Higashi-Shimbashi, Minato, Tokyo 105-0021, Japan",
      "lat": 35.663,
      "lng": 139.75992,
      "duration": 10
    },
    {
      "address": "2-7-2 Higashi-Shimbashi, Minato, Tokyo 105-0021, Japan",
      "lat": 35.66173,
      "lng": 139.75686,
      "duration": 10
    },
    {
      "address": "3-7-3 Higashi-Shimbashi, Minato, Tokyo 105-0021, Japan",
      "lat": 35.66291,
      "lng": 139.75974,
      "duration": 15
    },
    {
      "address": "1-8-1 Higashi-Ikebukuro, Toshima, Tokyo 170-0013, Japan",
      "lat": 35.73132,
      "lng": 139.71449,
      "duration": 10
    },
    {
      "address": "2-8-2 Higashi-Ikebukuro, Toshima, Tokyo 170-0013, Japan",
      "lat": 35.73263,
      "lng": 139.72095,
      "duration": 10
    },
    {
      "address": "4-8-4 Higashi-Ikebukuro, Toshima, Tokyo 170-0013, Japan",
      "lat": 35.72732,
      "lng": 139.7184,
      "duration": 20
    },
    {
      "address": "1-9-1 Takadanobaba, Shinjuku, Tokyo 169-0075, Japan",
      "lat": 35.70953,
      "lng": 139.70889,
      "duration": 10
    },
    {
      "address": "3-9-3 Takadanobaba, Shinjuku, Tokyo 169-0075, Japan",
      "lat": 35.7144,
      "lng": 139.70005,
      "duration": 10
    },
    {
      "address": "5-9-5 Takadanobaba, Shinjuku, Tokyo 169-0075, Japan",
      "lat": 35.71183,
      "lng": 139.70195,
      "duration": 15
    },
    {
      "address": "1-10-1 Kabukicho, Shinjuku, Tokyo 160-0021, Japan",
      "lat": 35.69512,
      "lng": 139.70339,
      "duration": 10
    },
    {
      "address": "2-10-2 Kabukicho, Shinjuku, Tokyo 160-0021, Japan",
      "lat": 35.69496,
      "lng": 139.70471,
      "duration": 10
    },
    {
      "address": "3-10-3 Kabukicho, Shinjuku, Tokyo 160-0021, Japan",
      "lat": 35.69594,
      "lng": 139.70304,
      "duration": 15
    },
    {
      "address": "2-11-2 Nihonbashi, Chuo, Tokyo 103-0027, Japan",
      "lat": 35.68041,
      "lng": 139.77479,
      "duration": 20
    },
    {
      "address": "4-11-4 Nihonbashi, Chuo, Tokyo 103-0027, Japan",
      "lat": 35.68155,
      "lng": 139.7744,
      "duration": 10
    },
    {
      "address": "4-12-4 Kasumigaseki, Chiyoda, Tokyo 100-0013, Japan",
      "lat": 35.67367,
      "lng": 139.75044,
      "duration": 15
    },
    {
      "address": "2-13-2 Yoyogi-Kamizono-cho, Shibuya, Tokyo 151-0052, Japan",
      "lat": 35.67413,
      "lng": 139.69752,
      "duration": 10
    },
    {
      "address": "1-14-1 Ueno, Taito, Tokyo 110-0005, Japan",
      "lat": 35.70654,
      "lng": 139.7703,
      "duration": 10
    },
    {
      "address": "1-15-1 Akihabara, Chiyoda, Tokyo 101-0021, Japan",
      "lat": 35.70117,
      "lng": 139.77055,
      "duration": 15
    },
    {
      "address": "5-16-5 Roppongi, Minato, Tokyo 106-0032, Japan",
      "lat": 35.66179,
      "lng": 139.73496,
      "duration": 10
    },
    {
      "address": "1-17-1 Ginza, Chuo, Tokyo 104-0061, Japan",
      "lat": 35.67395,
      "lng": 139.77175,
      "duration": 20
    },
    {
      "address": "3-18-3 Odaiba, Minato, Tokyo 135-0091, Japan",
      "lat": 35.63078,
      "lng": 139.77327,
      "duration": 15
    },
    {
      "address": "1-19-1 Nakano, Nakano, Tokyo 164-0001, Japan",
      "lat": 35.70449,
      "lng": 139.67712,
      "duration": 10
    },
    {
      "address": "2-19-2 Nakano, Nakano, Tokyo 164-0001, Japan",
      "lat": 35.70285,
      "lng": 139.66783,
      "duration": 10
    },
    {
      "address": "3-19-3 Nakano, Nakano, Tokyo 164-0001, Japan",
      "lat": 35.70303,
      "lng": 139.66163,
      "duration": 15
    },
    {
      "address": "4-19-4 Nakano, Nakano, Tokyo 164-0001, Japan",
      "lat": 35.70573,
      "lng": 139.65898,
      "duration": 10
    },
    {
      "address": "5-19-5 Nakano, Nakano, Tokyo 164-0001, Japan",
      "lat": 35.70739,
      "lng": 139.6703,
      "duration": 10
    },
    {
      "address": "1-20-1 Kichijoji, Musashino, Tokyo 180-0004, Japan",
      "lat": 35.70571,
      "lng": 139.57507,
      "duration": 20
    },
    {
      "address": "1-22-1 Meguro, Meguro, Tokyo 153-0063, Japan",
      "lat": 35.63603,
      "lng": 139.71124,
      "duration": 10
    },
    {
      "address": "5-22-5 Meguro, Meguro, Tokyo 153-0063, Japan",
      "lat": 35.63448,
      "lng": 139.70659,
      "duration": 10
    },
    {
      "address": "1-23-1 Gotanda, Shinagawa, Tokyo 141-0031, Japan",
      "lat": 35.62463,
      "lng": 139.71682,
      "duration": 15
    },
    {
      "address": "2-24-2 Ebisu, Shibuya, Tokyo 150-0013, Japan",
      "lat": 35.6475,
      "lng": 139.7203,
      "duration": 10
    },
    {
      "address": "3-24-3 Ebisu, Shibuya, Tokyo 150-0013, Japan",
      "lat": 35.64315,
      "lng": 139.71721,
      "duration": 10
    },
    {
      "address": "4-24-4 Ebisu, Shibuya, Tokyo 150-0013, Japan",
      "lat": 35.64534,
      "lng": 139.71601,
      "duration": 15
    },
    {
      "address": "5-24-5 Ebisu, Shibuya, Tokyo 150-0013, Japan",
      "lat": 35.64533,
      "lng": 139.7165,
      "duration": 20
    }
  ],
  "sydney": [
    {
      "address": "Bennelong Point, Sydney NSW 2000, Australia",
      "lat": -33.85741,
      "lng": 151.21439,
      "duration": 0
    },
    {
      "address": "1 George St, Sydney NSW 2000, Australia",
      "lat": -33.85784,
      "lng": 151.20894,
      "duration": 10
    },
    {
      "address": "10 George St, Sydney NSW 2000, Australia",
      "lat": -33.86775,
      "lng": 151.283,
      "duration": 10
    },
    {
      "address": "20 George St, Sydney NSW 2000, Australia",
      "lat": -33.86754,
      "lng": 151.28138,
      "duration": 15
    },
    {
      "address": "1 Pitt St, Sydney NSW 2000, Australia",
      "lat": -33.86196,
      "lng": 151.20919,
      "duration": 10
    },
    {
      "address": "10 Pitt St, Sydney NSW 2000, Australia",
      "lat": -33.86168,
      "lng": 151.20921,
      "duration": 10
    },
    {
      "address": "20 Pitt St, Sydney NSW 2000, Australia",
      "lat": -33.86217,
      "lng": 151.20915,
      "duration": 15
    },
    {
      "address": "1 Castlereagh St, Sydney NSW 2000, Australia",
      "lat": -33.86641,
      "lng": 151.21,
      "duration": 20
    },
    {
      "address": "10 Castlereagh St, Sydney NSW 2000, Australia",
      "lat": -33.86679,
      "lng": 151.20994,
      "duration": 10
    },
    {
      "address": "20 Castlereagh St, Sydney NSW 2000, Australia",
      "lat": -33.86742,
      "lng": 151.20987,
      "duration": 15
    },
    {
      "address": "1 Macquarie St, Sydney NSW 2000, Australia",
      "lat": -33.85936,
      "lng": 151.21342,
      "duration": 10
    },
    {
      "address": "10 Macquarie St, Sydney NSW 2000, Australia",
      "lat": -33.86895,
      "lng": 151.21212,
      "duration": 10
    },
    {
      "address": "20 Macquarie St, Sydney NSW 2000, Australia",
      "lat": -33.88566,
      "lng": 151.1636,
      "duration": 15
    },
    {
      "address": "1 Oxford St, Darlinghurst NSW 2010, Australia",
      "lat": -33.87718,
      "lng": 151.2127,
      "duration": 10
    },
    {
      "address": "10 Oxford St, Darlinghurst NSW 2010, Australia",
      "lat": -33.87734,
      "lng": 151.2129,
      "duration": 20
    },
    {
      "address": "20 Oxford St, Darlinghurst NSW 2010, Australia",
      "lat": -33.87749,
      "lng": 151.21309,
      "duration": 15
    },
    {
      "address": "1 Crown St, Surry Hills NSW 2010, Australia",
      "lat": -33.87469,
      "lng": 151.21624,
      "duration": 10
    },
    {
      "address": "20 Crown St, Surry Hills NSW 2010, Australia",
      "lat": -33.87468,
      "lng": 151.21624,
      "duration": 10
    },
    {
      "address": "1 King St, Newtown NSW 2042, Australia",
      "lat": -33.89165,
      "lng": 151.18806,
      "duration": 15
    },
    {
      "address": "10 King St, Newtown NSW 2042, Australia",
      "lat": -33.89229,
      "lng": 151.18727,
      "duration": 10
    },
    {
      "address": "20 King St, Newtown NSW 2042, Australia",
      "lat": -33.89237,
      "lng": 151.18709,
      "duration": 10
    },
    {
      "address": "1 Glebe Point Rd, Glebe NSW 2037, Australia",
      "lat": -33.88423,
      "lng": 151.19272,
      "duration": 20
    },
    {
      "address": "10 Glebe Point Rd, Glebe NSW 2037, Australia",
      "lat": -33.88414,
      "lng": 151.19259,
      "duration": 10
    },
    {
      "address": "20 Glebe Point Rd, Glebe NSW 2037, Australia",
      "lat": -33.88406,
      "lng": 151.19248,
      "duration": 10
    },
    {
      "address": "1 Parramatta Rd, Leichhardt NSW 2040, Australia",
      "lat": -33.88907,
      "lng": 151.14388,
      "duration": 15
    },
    {
      "address": "10 Parramatta Rd, Leichhardt NSW 2040, Australia",
      "lat": -33.86628,
      "lng": 151.09321,
      "duration": 10
    },
    {
      "address": "20 Parramatta Rd, Leichhardt NSW 2040, Australia",
      "lat": -33.88768,
      "lng": 151.17121,
      "duration": 10
    },
    {
      "address": "1 Military Rd, Neutral Bay NSW 2089, Australia",
      "lat": -33.82927,
      "lng": 151.2158,
      "duration": 15
    },
    {
      "address": "10 Military Rd, Neutral Bay NSW 2089, Australia",
      "lat": -33.82921,
      "lng": 151.21567,
      "duration": 20
    },
    {
      "address": "20 Military Rd, Neutral Bay NSW 2089, Australia",
      "lat": -33.82932,
      "lng": 151.21624,
      "duration": 10
    },
    {
      "address": "1 Miller St, North Sydney NSW 2060, Australia",
      "lat": -33.84196,
      "lng": 151.20623,
      "duration": 15
    },
    {
      "address": "10 Miller St, North Sydney NSW 2060, Australia",
      "lat": -33.84237,
      "lng": 151.20615,
      "duration": 10
    },
    {
      "address": "20 Miller St, North Sydney NSW 2060, Australia",
      "lat": -33.84069,
      "lng": 151.20649,
      "duration": 10
    },
    {
      "address": "1 Pacific Hwy, St Leonards NSW 2065, Australia",
      "lat": -33.84118,
      "lng": 151.20899,
      "duration": 15
    },
    {
      "address": "10 Pacific Hwy, St Leonards NSW 2065, Australia",
      "lat": -33.82362,
      "lng": 151.1938,
      "duration": 10
    },
    {
      "address": "20 Pacific Hwy, St Leonards NSW 2065, Australia",
      "lat": -33.8237,
      "lng": 151.19354,
      "duration": 20
    },
    {
      "address": "1 Anzac Pde, Kensington NSW 2033, Australia",
      "lat": -33.90419,
      "lng": 151.22382,
      "duration": 15
    },
    {
      "address": "10 Anzac Pde, Kensington NSW 2033, Australia",
      "lat": -33.90327,
      "lng": 151.22354,
      "duration": 10
    },
    {
      "address": "1 Botany Rd, Alexandria NSW 2015, Australia",
      "lat": -33.89516,
      "lng": 151.1991,
      "duration": 10
    },
    {
      "address": "10 Botany Rd, Alexandria NSW 2015, Australia",
      "lat": -33.89548,
      "lng": 151.19898,
      "duration": 15
    },
    {
      "address": "1 Cleveland St, Redfern NSW 2016, Australia",
      "lat": -33.89517,
      "lng": 151.21977,
      "duration": 10
    },
    {
      "address": "10 Cleveland St, Redfern NSW 2016, Australia",
      "lat": -33.88789,
      "lng": 151.19381,
      "duration": 10
    },
    {
      "address": "20 Cleveland St, Redfern NSW 2016, Australia",
      "lat": -33.88792,
      "lng": 151.19403,
      "duration": 20
    },
    {
      "address": "1 Harris St, Pyrmont NSW 2009, Australia",
      "lat": -33.86566,
      "lng": 151.19103,
      "duration": 10
    },
    {
      "address": "10 Harris St, Pyrmont NSW 2009, Australia",
      "lat": -33.86578,
      "lng": 151.19168,
      "duration": 10
    },
    {
      "address": "20 Harris St, Pyrmont NSW 2009, Australia",
      "lat": -33.86623,
      "lng": 151.19193,
      "duration": 15
    },
    {
      "address": "1 Darling Dr, Sydney NSW 2000, Australia",
      "lat": -33.8702,
      "lng": 151.1981,
      "duration": 10
    },
    {
      "address": "10 Darling Dr, Sydney NSW 2000, Australia",
      "lat": -33.87159,
      "lng": 151.19842,
      "duration": 10
    },
    {
      "address": "20 Darling Dr, Sydney NSW 2000, Australia",
      "lat": -33.87441,
      "lng": 151.1985,
      "duration": 15
    },
    {
      "address": "1 Barangaroo Ave, Barangaroo NSW 2000, Australia",
      "lat": -33.86239,
      "lng": 151.2015,
      "duration": 20
    }
  ],
  "toronto": [
    {
      "address": "301 Front St W, Toronto, ON M5V 2T6, Canada",
      "lat": 43.64284,
      "lng": -79.38577,
      "duration": 0
    },
    {
      "address": "1 Yonge St, Toronto, ON M5E 1W7, Canada",
      "lat": 43.6422,
      "lng": -79.37483,
      "duration": 10
    },
    {
      "address": "10 Yonge St, Toronto, ON M5E 1W7, Canada",
      "lat": 43.64261,
      "lng": -79.3751,
      "duration": 10
    },
    {
      "address": "20 Yonge St, Toronto, ON M5E 1W7, Canada",
      "lat": 43.64463,
      "lng": -79.376,
      "duration": 15
    },
    {
      "address": "1 Bay St, Toronto, ON M5J 2R8, Canada",
      "lat": 43.64129,
      "lng": -79.37697,
      "duration": 10
    },
    {
      "address": "10 Bay St, Toronto, ON M5J 2R8, Canada",
      "lat": 43.64193,
      "lng": -79.37805,
      "duration": 10
    },
    {
      "address": "1 King St W, Toronto, ON M5H 1A1, Canada",
      "lat": 43.64914,
      "lng": -79.37812,
      "duration": 15
    },
    {
      "address": "10 King St W, Toronto, ON M5H 1A1, Canada",
      "lat": 43.64911,
      "lng": -79.37831,
      "duration": 20
    },
    {
      "address": "20 King St W, Toronto, ON M5H 1A1, Canada",
      "lat": 43.64901,
      "lng": -79.37874,
      "duration": 10
    },
    {
      "address": "1 Queen St W, Toronto, ON M5H 2M9, Canada",
      "lat": 43.65238,
      "lng": -79.37937,
      "duration": 15
    },
    {
      "address": "10 Queen St W, Toronto, ON M5H 2M9, Canada",
      "lat": 43.6523,
      "lng": -79.37978,
      "duration": 10
    },
    {
      "address": "20 Queen St W, Toronto, ON M5H 2M9, Canada",
      "lat": 43.65214,
      "lng": -79.38052,
      "duration": 10
    },
    {
      "address": "1 Bloor St W, Toronto, ON M4W 1A9, Canada",
      "lat": 43.67017,
      "lng": -79.38705,
      "duration": 15
    },
    {
      "address": "10 Bloor St W, Toronto, ON M4W 1A9, Canada",
      "lat": 43.66996,
      "lng": -79.3882,
      "duration": 10
    },
    {
      "address": "20 Bloor St W, Toronto, ON M4W 1A9, Canada",
      "lat": 43.66994,
      "lng": -79.3883,
      "duration": 20
    },
    {
      "address": "1 College St, Toronto, ON M5S 3H7, Canada",
      "lat": 43.66132,
      "lng": -79.38341,
      "duration": 15
    },
    {
      "address": "10 College St, Toronto, ON M5S 3H7, Canada",
      "lat": 43.66128,
      "lng": -79.38358,
      "duration": 10
    },
    {
      "address": "20 College St, Toronto, ON M5S 3H7, Canada",
      "lat": 43.66121,
      "lng": -79.38391,
      "duration": 10
    },
    {
      "address": "1 Spadina Ave, Toronto, ON M5T 2G3, Canada",
      "lat": 43.64002,
      "lng": -79.39266,
      "duration": 15
    },
    {
      "address": "10 Spadina Ave, Toronto, ON M5T 2G3, Canada",
      "lat": 43.64311,
      "lng": -79.39421,
      "duration": 10
    },
    {
      "address": "20 Spadina Ave, Toronto, ON M5T 2G3, Canada",
      "lat": 43.64343,
      "lng": -79.39433,
      "duration": 10
    },
    {
      "address": "1 Bathurst St, Toronto, ON M5V 2P1, Canada",
      "lat": 43.63576,
      "lng": -79.39841,
      "duration": 20
    },
    {
      "address": "10 Bathurst St, Toronto, ON M5V 2P1, Canada",
      "lat": 43.63604,
      "lng": -79.39892,
      "duration": 10
    },
    {
      "address": "20 Bathurst St, Toronto, ON M5V 2P1, Canada",
      "lat": 43.6372,
      "lng": -79.39997,
      "duration": 10
    },
    {
      "address": "1 Dundas St W, Toronto, ON M5G 1Z3, Canada",
      "lat": 43.65604,
      "lng": -79.38083,
      "duration": 15
    },
    {
      "address": "10 Dundas St W, Toronto, ON M5G 1Z3, Canada",
      "lat": 43.65625,
      "lng": -79.38125,
      "duration": 10
    },
    {
      "address": "20 Dundas St W, Toronto, ON M5G 1Z3, Canada",
      "lat": 43.6562,
      "lng": -79.38148,
      "duration": 10
    },
    {
      "address": "1 Carlton St, Toronto, ON M5B 1L3, Canada",
      "lat": 43.6614,
      "lng": -79.38277,
      "duration": 15
    },
    {
      "address": "10 Carlton St, Toronto, ON M5B 1L3, Canada",
      "lat": 43.66139,
      "lng": -79.38224,
      "duration": 20
    },
    {
      "address": "20 Carlton St, Toronto, ON M5B 1L3, Canada",
      "lat": 43.6614,
      "lng": -79.38145,
      "duration": 10
    },
    {
      "address": "1 Jarvis St, Toronto, ON M5C 2H8, Canada",
      "lat": 43.64961,
      "lng": -79.37153,
      "duration": 15
    },
    {
      "address": "10 Jarvis St, Toronto, ON M5C 2H8, Canada",
      "lat": 43.64977,
      "lng": -79.3716,
      "duration": 10
    },
    {
      "address": "20 Jarvis St, Toronto, ON M5C 2H8, Canada",
      "lat": 43.64997,
      "lng": -79.37168,
      "duration": 10
    },
    {
      "address": "1 Parliament St, Toronto, ON M5A 2Z4, Canada",
      "lat": 43.64654,
      "lng": -79.3618,
      "duration": 15
    },
    {
      "address": "10 Parliament St, Toronto, ON M5A 2Z4, Canada",
      "lat": 43.64881,
      "lng": -79.36155,
      "duration": 10
    },
    {
      "address": "20 Parliament St, Toronto, ON M5A 2Z4, Canada",
      "lat": 43.64901,
      "lng": -79.36163,
      "duration": 20
    },
    {
      "address": "1 Danforth Ave, Toronto, ON M4K 1N2, Canada",
      "lat": 43.67629,
      "lng": -79.35848,
      "duration": 15
    },
    {
      "address": "10 Danforth Ave, Toronto, ON M4K 1N2, Canada",
      "lat": 43.67612,
      "lng": -79.35927,
      "duration": 10
    },
    {
      "address": "20 Danforth Ave, Toronto, ON M4K 1N2, Canada",
      "lat": 43.67613,
      "lng": -79.35924,
      "duration": 10
    },
    {
      "address": "1 Queen St E, Toronto, ON M5C 3G5, Canada",
      "lat": 43.65252,
      "lng": -79.37873,
      "duration": 15
    },
    {
      "address": "10 Queen St E, Toronto, ON M5C 3G5, Canada",
      "lat": 43.65253,
      "lng": -79.37872,
      "duration": 10
    },
    {
      "address": "20 Queen St E, Toronto, ON M5C 3G5, Canada",
      "lat": 43.65261,
      "lng": -79.37834,
      "duration": 10
    },
    {
      "address": "1 Richmond St W, Toronto, ON M5H 2A4, Canada",
      "lat": 43.6516,
      "lng": -79.37934,
      "duration": 20
    },
    {
      "address": "10 Richmond St W, Toronto, ON M5H 2A4, Canada",
      "lat": 43.6516,
      "lng": -79.37935,
      "duration": 10
    },
    {
      "address": "20 Richmond St W, Toronto, ON M5H 2A4, Canada",
      "lat": 43.65148,
      "lng": -79.37989,
      "duration": 10
    },
    {
      "address": "1 Adelaide St W, Toronto, ON M5H 1P6, Canada",
      "lat": 43.6504,
      "lng": -79.37861,
      "duration": 15
    },
    {
      "address": "10 Adelaide St W, Toronto, ON M5H 1P6, Canada",
      "lat": 43.65033,
      "lng": -79.37892,
      "duration": 10
    },
    {
      "address": "20 Adelaide St W, Toronto, ON M5H 1P6, Canada",
      "lat": 43.65025,
      "lng": -79.37925,
      "duration": 10
    },
    {
      "address": "1 Wellington St W, Toronto, ON M5J 2T3, Canada",
      "lat": 43.64776,
      "lng": -79.3777,
      "duration": 15
    },
    {
      "address": "10 Wellington St W, Toronto, ON M5J 2T3, Canada",
      "lat": 43.64768,
      "lng": -79.37808,
      "duration": 20
    }
  ],
  "singapore": [
    {
      "address": "Gardens by the Bay, 18 Marina Gardens Dr, Singapore",
      "lat": 1.28196,
      "lng": 103.86575,
      "duration": 0
    },
    {
      "address": "Marina Bay Sands, Singapore",
      "lat": 1.28486,
      "lng": 103.85881,
      "duration": 10
    },
    {
      "address": "Merlion Park, Singapore",
      "lat": 1.28706,
      "lng": 103.85332,
      "duration": 10
    },
    {
      "address": "ION Orchard, Singapore",
      "lat": 1.3011,
      "lng": 103.83967,
      "duration": 15
    },
    {
      "address": "VivoCity, Singapore",
      "lat": 1.26506,
      "lng": 103.82247,
      "duration": 10
    },
    {
      "address": "Jewel Changi Airport, Singapore",
      "lat": 1.3611,
      "lng": 103.98994,
      "duration": 10
    },
    {
      "address": "Universal Studios Singapore, Sentosa",
      "lat": 1.25639,
      "lng": 103.82157,
      "duration": 15
    },
    {
      "address": "Bugis Junction, Singapore",
      "lat": 1.29976,
      "lng": 103.85544,
      "duration": 20
    },
    {
      "address": "Raffles City, Singapore",
      "lat": 1.29447,
      "lng": 103.85286,
      "duration": 10
    },
    {
      "address": "Clarke Quay, Singapore",
      "lat": 1.28987,
      "lng": 103.84591,
      "duration": 15
    },
    {
      "address": "Chinatown Complex, Singapore",
      "lat": 1.28178,
      "lng": 103.84321,
      "duration": 10
    },
    {
      "address": "Mustafa Centre, Little India, Singapore",
      "lat": 1.30988,
      "lng": 103.8553,
      "duration": 10
    },
    {
      "address": "Sultan Mosque, Kampong Glam, Singapore",
      "lat": 1.30368,
      "lng": 103.86109,
      "duration": 15
    },
    {
      "address": "East Coast Park, Singapore",
      "lat": 1.30076,
      "lng": 103.9122,
      "duration": 10
    },
    {
      "address": "Holland Village, Singapore",
      "lat": 1.35275,
      "lng": 103.82006,
      "duration": 20
    },
    {
      "address": "Tiong Bahru Plaza, Singapore",
      "lat": 1.28955,
      "lng": 103.83207,
      "duration": 15
    },
    {
      "address": "Jurong Point, Singapore",
      "lat": 1.34002,
      "lng": 103.70712,
      "duration": 10
    },
    {
      "address": "NEX Serangoon, Singapore",
      "lat": 1.35096,
      "lng": 103.87296,
      "duration": 10
    },
    {
      "address": "Westgate, Jurong East, Singapore",
      "lat": 1.33478,
      "lng": 103.7428,
      "duration": 15
    },
    {
      "address": "Parkway Parade, Singapore",
      "lat": 1.30097,
      "lng": 103.90619,
      "duration": 10
    },
    {
      "address": "National Gallery Singapore",
      "lat": 1.28947,
      "lng": 103.85157,
      "duration": 10
    },
    {
      "address": "Singapore Botanic Gardens",
      "lat": 1.31518,
      "lng": 103.8164,
      "duration": 20
    },
    {
      "address": "Plaza Singapura, Singapore",
      "lat": 1.35823,
      "lng": 103.94346,
      "duration": 10
    },
    {
      "address": "Funan Mall, Singapore",
      "lat": 1.29097,
      "lng": 103.84983,
      "duration": 10
    },
    {
      "address": "Suntec City, Singapore",
      "lat": 1.29489,
      "lng": 103.85854,
      "duration": 15
    },
    {
      "address": "Marina Square, Singapore",
      "lat": 1.2918,
      "lng": 103.85613,
      "duration": 10
    },
    {
      "address": "Esplanade Theatres on the Bay, Singapore",
      "lat": 1.29033,
      "lng": 103.85589,
      "duration": 10
    },
    {
      "address": "Fullerton Hotel, Singapore",
      "lat": 1.28557,
      "lng": 103.85291,
      "duration": 15
    },
    {
      "address": "Lau Pa Sat, Singapore",
      "lat": 1.2804,
      "lng": 103.85083,
      "duration": 20
    },
    {
      "address": "Maxwell Food Centre, Singapore",
      "lat": 1.28018,
      "lng": 103.84454,
      "duration": 10
    },
    {
      "address": "JEM, Jurong East, Singapore",
      "lat": 1.33247,
      "lng": 103.74345,
      "duration": 15
    },
    {
      "address": "Causeway Point, Woodlands, Singapore",
      "lat": 1.43615,
      "lng": 103.78599,
      "duration": 10
    },
    {
      "address": "Waterway Point, Punggol, Singapore",
      "lat": 1.40699,
      "lng": 103.90142,
      "duration": 10
    },
    {
      "address": "Compass One, Sengkang, Singapore",
      "lat": 1.3921,
      "lng": 103.89465,
      "duration": 15
    },
    {
      "address": "Bedok Mall, Singapore",
      "lat": 1.32408,
      "lng": 103.92944,
      "duration": 10
    },
    {
      "address": "Tampines Mall, Singapore",
      "lat": 1.35288,
      "lng": 103.9444,
      "duration": 20
    },
    {
      "address": "White Sands, Pasir Ris, Singapore",
      "lat": 1.37272,
      "lng": 103.95003,
      "duration": 15
    },
    {
      "address": "City Square Mall, Singapore",
      "lat": 1.31134,
      "lng": 103.85592,
      "duration": 10
    },
    {
      "address": "United Square, Novena, Singapore",
      "lat": 1.31651,
      "lng": 103.84367,
      "duration": 10
    },
    {
      "address": "Tanglin Mall, Singapore",
      "lat": 1.30257,
      "lng": 103.83767,
      "duration": 15
    },
    {
      "address": "Great World City, Singapore",
      "lat": 1.29249,
      "lng": 103.83198,
      "duration": 10
    },
    {
      "address": "Alexandra Retail Centre, Singapore",
      "lat": 1.27415,
      "lng": 103.80115,
      "duration": 10
    },
    {
      "address": "Gillman Barracks, Singapore",
      "lat": 1.27902,
      "lng": 103.80488,
      "duration": 20
    },
    {
      "address": "Singapore Zoo, Mandai, Singapore",
      "lat": 1.41076,
      "lng": 103.77822,
      "duration": 10
    },
    {
      "address": "Night Safari Singapore, Mandai",
      "lat": 1.4043,
      "lng": 103.78834,
      "duration": 10
    },
    {
      "address": "Haji Lane, Kampong Glam, Singapore",
      "lat": 1.30237,
      "lng": 103.85968,
      "duration": 15
    },
    {
      "address": "Fort Canning Park, Singapore",
      "lat": 1.29624,
      "lng": 103.84614,
      "duration": 10
    },
    {
      "address": "Changi Village, Singapore",
      "lat": 1.33216,
      "lng": 103.94634,
      "duration": 10
    },
    {
      "address": "Pulau Ubin Ferry Terminal, Changi Point, Singapore",
      "lat": 1.38761,
      "lng": 103.99963,
      "duration": 15
    },
    {
      "address": "Bukit Timah Nature Reserve, Singapore",
      "lat": 1.35456,
      "lng": 103.77652,
      "duration": 20
    }
  ],
  "dubai": [
    {
      "address": "1 Sheikh Mohammed bin Rashid Blvd, Dubai, UAE",
      "lat": 25.19773,
      "lng": 55.27434,
      "duration": 0
    },
    {
      "address": "The Dubai Mall, Downtown Dubai, UAE",
      "lat": 25.1989,
      "lng": 55.27975,
      "duration": 10
    },
    {
      "address": "Mall of the Emirates, Sheikh Zayed Road, Dubai, UAE",
      "lat": 25.17156,
      "lng": 55.24239,
      "duration": 10
    },
    {
      "address": "Dubai Marina Mall, Dubai Marina, UAE",
      "lat": 25.07585,
      "lng": 55.14063,
      "duration": 15
    },
    {
      "address": "Ibn Battuta Mall, Jebel Ali, Dubai, UAE",
      "lat": 25.04637,
      "lng": 55.11983,
      "duration": 10
    },
    {
      "address": "Deira City Centre, Port Saeed, Dubai, UAE",
      "lat": 25.25219,
      "lng": 55.3333,
      "duration": 10
    },
    {
      "address": "Dubai Festival City Mall, Dubai, UAE",
      "lat": 25.22208,
      "lng": 55.35367,
      "duration": 15
    },
    {
      "address": "Mercato Shopping Mall, Jumeirah Beach Road, Dubai, UAE",
      "lat": 25.21678,
      "lng": 55.25237,
      "duration": 20
    },
    {
      "address": "City Centre Mirdif, Dubai, UAE",
      "lat": 25.1081,
      "lng": 55.36141,
      "duration": 10
    },
    {
      "address": "Souk Madinat Jumeirah, Dubai, UAE",
      "lat": 25.13332,
      "lng": 55.18691,
      "duration": 15
    },
    {
      "address": "Gold Souk, Deira, Dubai, UAE",
      "lat": 25.27036,
      "lng": 55.29914,
      "duration": 10
    },
    {
      "address": "Spice Souk, Deira, Dubai, UAE",
      "lat": 25.2675,
      "lng": 55.29806,
      "duration": 10
    },
    {
      "address": "Dubai Frame, Zabeel Park, Dubai, UAE",
      "lat": 25.26752,
      "lng": 55.29262,
      "duration": 15
    },
    {
      "address": "Museum of the Future, Sheikh Zayed Road, Dubai, UAE",
      "lat": 25.21925,
      "lng": 55.28137,
      "duration": 10
    },
    {
      "address": "Jumeirah Beach Hotel, Dubai, UAE",
      "lat": 25.14139,
      "lng": 55.19077,
      "duration": 20
    },
    {
      "address": "Atlantis The Palm, Crescent Road, Dubai, UAE",
      "lat": 25.13202,
      "lng": 55.11729,
      "duration": 15
    },
    {
      "address": "Dubai Creek Harbour, Dubai, UAE",
      "lat": 25.20582,
      "lng": 55.34464,
      "duration": 10
    },
    {
      "address": "Al Seef, Dubai Creek, Dubai, UAE",
      "lat": 25.26451,
      "lng": 55.29792,
      "duration": 10
    },
    {
      "address": "La Mer, Jumeirah 1, Dubai, UAE",
      "lat": 25.2293,
      "lng": 55.25891,
      "duration": 15
    },
    {
      "address": "Kite Beach, Jumeirah, Dubai, UAE",
      "lat": 25.20722,
      "lng": 55.24696,
      "duration": 10
    },
    {
      "address": "Al Mamzar Beach Park, Dubai, UAE",
      "lat": 25.31724,
      "lng": 55.34706,
      "duration": 10
    },
    {
      "address": "Dubai Opera, Downtown Dubai, UAE",
      "lat": 25.09723,
      "lng": 55.17467,
      "duration": 20
    },
    {
      "address": "Emirates Towers, Sheikh Zayed Road, Dubai, UAE",
      "lat": 25.21689,
      "lng": 55.27979,
      "duration": 10
    },
    {
      "address": "World Trade Centre, Sheikh Zayed Road, Dubai, UAE",
      "lat": 25.21815,
      "lng": 55.2793,
      "duration": 10
    },
    {
      "address": "Dubai Design District, Dubai, UAE",
      "lat": 25.18619,
      "lng": 55.29828,
      "duration": 15
    },
    {
      "address": "Boxpark, Al Wasl Road, Dubai, UAE",
      "lat": 25.2004,
      "lng": 55.2491,
      "duration": 10
    },
    {
      "address": "City Walk, Al Safa Street, Dubai, UAE",
      "lat": 25.20931,
      "lng": 55.26219,
      "duration": 10
    },
    {
      "address": "Ain Dubai, Bluewaters Island, Dubai, UAE",
      "lat": 25.07987,
      "lng": 55.12214,
      "duration": 15
    },
    {
      "address": "Dubai Hills Mall, Al Khail Road, Dubai, UAE",
      "lat": 25.04775,
      "lng": 55.19671,
      "duration": 20
    },
    {
      "address": "Dubai Outlet Mall, Dubai-Al Ain Road, UAE",
      "lat": 25.0729,
      "lng": 55.40104,
      "duration": 10
    },
    {
      "address": "Dragon Mart, International City, Dubai, UAE",
      "lat": 25.17034,
      "lng": 55.41411,
      "duration": 15
    },
    {
      "address": "IMG Worlds of Adventure, Sheikh Mohammed Bin Zayed Road, Dubai, UAE",
      "lat": 25.09524,
      "lng": 55.32793,
      "duration": 10
    },
    {
      "address": "Dubai Parks and Resorts, Sheikh Zayed Road, Dubai, UAE",
      "lat": 25.16554,
      "lng": 55.23514,
      "duration": 10
    },
    {
      "address": "Legoland Dubai, Sheikh Zayed Road, Dubai, UAE",
      "lat": 25.21698,
      "lng": 55.27889,
      "duration": 15
    },
    {
      "address": "Motiongate Dubai, Dubai Parks and Resorts, UAE",
      "lat": 24.9238,
      "lng": 55.00624,
      "duration": 10
    },
    {
      "address": "Dubai Autodrome, Motor City, Dubai, UAE",
      "lat": 25.0482,
      "lng": 55.23735,
      "duration": 20
    },
    {
      "address": "Al Safa Park, Sheikh Zayed Road, Dubai, UAE",
      "lat": 25.17223,
      "lng": 55.24132,
      "duration": 15
    },
    {
      "address": "Zabeel Park, Zaabeel, Dubai, UAE",
      "lat": 25.22881,
      "lng": 55.29273,
      "duration": 10
    },
    {
      "address": "Jumeirah Lakes Towers, Cluster Y, Dubai, UAE",
      "lat": 25.07796,
      "lng": 55.15414,
      "duration": 10
    },
    {
      "address": "Business Bay, Executive Towers, Dubai, UAE",
      "lat": 25.19265,
      "lng": 55.26706,
      "duration": 15
    },
    {
      "address": "DIFC Gate Village, Dubai, UAE",
      "lat": 25.21226,
      "lng": 55.28221,
      "duration": 10
    },
    {
      "address": "Al Barsha, Mall of the Emirates area, Dubai, UAE",
      "lat": 25.11615,
      "lng": 55.2004,
      "duration": 10
    },
    {
      "address": "Al Quoz, Alserkal Avenue, Dubai, UAE",
      "lat": 25.1408,
      "lng": 55.2265,
      "duration": 20
    },
    {
      "address": "Palm Jumeirah, The Pointe, Dubai, UAE",
      "lat": 25.1258,
      "lng": 55.12435,
      "duration": 10
    },
    {
      "address": "Dubai Healthcare City, Dubai, UAE",
      "lat": 25.22889,
      "lng": 55.32406,
      "duration": 10
    },
    {
      "address": "Dubai International Airport, UAE",
      "lat": 25.25913,
      "lng": 55.37049,
      "duration": 15
    },
    {
      "address": "Burj Al Arab, Dubai, UAE",
      "lat": 25.14113,
      "lng": 55.18578,
      "duration": 10
    },
    {
      "address": "Dubai Creek Golf Club, Dubai, UAE",
      "lat": 25.05163,
      "lng": 55.26911,
      "duration": 10
    },
    {
      "address": "Mirdif City Centre, Dubai, UAE",
      "lat": 25.21626,
      "lng": 55.40528,
      "duration": 15
    },
    {
      "address": "Al Maktoum International Airport, Dubai, UAE",
      "lat": 24.88582,
      "lng": 55.15867,
      "duration": 20
    }
  ],
  "mumbai": [
    {
      "address": "Gateway of India, Apollo Bandar, Colaba, Mumbai, India",
      "lat": 18.9222,
      "lng": 72.83373,
      "duration": 0
    },
    {
      "address": "Chhatrapati Shivaji Terminus, Mumbai, India",
      "lat": 18.94013,
      "lng": 72.83643,
      "duration": 10
    },
    {
      "address": "Marine Drive, Mumbai, India",
      "lat": 18.94666,
      "lng": 72.82459,
      "duration": 10
    },
    {
      "address": "Haji Ali Dargah, Mumbai, India",
      "lat": 18.9822,
      "lng": 72.80879,
      "duration": 15
    },
    {
      "address": "Siddhivinayak Temple, Prabhadevi, Mumbai, India",
      "lat": 19.01615,
      "lng": 72.82852,
      "duration": 10
    },
    {
      "address": "Bandra-Worli Sea Link, Mumbai, India",
      "lat": 19.01257,
      "lng": 72.81669,
      "duration": 10
    },
    {
      "address": "Juhu Beach, Mumbai, India",
      "lat": 19.00529,
      "lng": 72.8429,
      "duration": 15
    },
    {
      "address": "Colaba Causeway, Mumbai, India",
      "lat": 18.91984,
      "lng": 72.83041,
      "duration": 20
    },
    {
      "address": "Crawford Market, Mumbai, India",
      "lat": 18.94637,
      "lng": 72.83465,
      "duration": 10
    },
    {
      "address": "Mahalaxmi Dhobi Ghat, Mumbai, India",
      "lat": 18.98223,
      "lng": 72.82548,
      "duration": 15
    },
    {
      "address": "Powai Lake, Mumbai, India",
      "lat": 19.11556,
      "lng": 72.90086,
      "duration": 10
    },
    {
      "address": "Phoenix Marketcity, Kurla, Mumbai, India",
      "lat": 19.08621,
      "lng": 72.88688,
      "duration": 10
    },
    {
      "address": "R City Mall, Ghatkopar, Mumbai, India",
      "lat": 19.09929,
      "lng": 72.91702,
      "duration": 15
    },
    {
      "address": "Inorbit Mall, Malad, Mumbai, India",
      "lat": 19.17279,
      "lng": 72.83418,
      "duration": 10
    },
    {
      "address": "Phoenix Palladium, Lower Parel, Mumbai, India",
      "lat": 18.99397,
      "lng": 72.82507,
      "duration": 20
    },
    {
      "address": "Nariman Point, Mumbai, India",
      "lat": 18.9259,
      "lng": 72.81886,
      "duration": 15
    },
    {
      "address": "Chhatrapati Shivaji Maharaj Vastu Sangrahalaya, Mumbai, India",
      "lat": 18.92648,
      "lng": 72.83153,
      "duration": 10
    },
    {
      "address": "Sanjay Gandhi National Park, Borivali, Mumbai, India",
      "lat": 19.23148,
      "lng": 72.86362,
      "duration": 10
    },
    {
      "address": "Film City, Goregaon, Mumbai, India",
      "lat": 19.1749,
      "lng": 72.86287,
      "duration": 15
    },
    {
      "address": "Global Vipassana Pagoda, Mumbai, India",
      "lat": 19.22825,
      "lng": 72.80489,
      "duration": 10
    },
    {
      "address": "Worli Sea Face, Mumbai, India",
      "lat": 19.01051,
      "lng": 72.81577,
      "duration": 10
    },
    {
      "address": "Dadar Flower Market, Mumbai, India",
      "lat": 19.01905,
      "lng": 72.84255,
      "duration": 20
    },
    {
      "address": "Hanging Gardens, Malabar Hill, Mumbai, India",
      "lat": 18.95741,
      "lng": 72.80541,
      "duration": 10
    },
    {
      "address": "Kamala Nehru Park, Mumbai, India",
      "lat": 18.95519,
      "lng": 72.80456,
      "duration": 10
    },
    {
      "address": "Nehru Science Centre, Worli, Mumbai, India",
      "lat": 18.99083,
      "lng": 72.81743,
      "duration": 15
    },
    {
      "address": "Mahalakshmi Temple, Mumbai, India",
      "lat": 19.06986,
      "lng": 72.89724,
      "duration": 10
    },
    {
      "address": "Bandra Bandstand, Mumbai, India",
      "lat": 19.04525,
      "lng": 72.81928,
      "duration": 10
    },
    {
      "address": "Carter Road, Bandra West, Mumbai, India",
      "lat": 19.06179,
      "lng": 72.82226,
      "duration": 15
    },
    {
      "address": "Linking Road, Bandra West, Mumbai, India",
      "lat": 19.06508,
      "lng": 72.83461,
      "duration": 20
    },
    {
      "address": "Hill Road, Bandra West, Mumbai, India",
      "lat": 19.05721,
      "lng": 72.82978,
      "duration": 10
    },
    {
      "address": "Oberoi Mall, Goregaon, Mumbai, India",
      "lat": 19.17376,
      "lng": 72.85956,
      "duration": 15
    },
    {
      "address": "Infiniti Mall, Malad, Mumbai, India",
      "lat": 19.18496,
      "lng": 72.83568,
      "duration": 10
    },
    {
      "address": "Hiranandani Gardens, Powai, Mumbai, India",
      "lat": 19.11524,
      "lng": 72.90952,
      "duration": 10
    },
    {
      "address": "IIT Bombay, Powai, Mumbai, India",
      "lat": 19.11938,
      "lng": 72.91229,
      "duration": 15
    },
    {
      "address": "Mumbai Central Station, Mumbai, India",
      "lat": 18.96872,
      "lng": 72.82203,
      "duration": 10
    },
    {
      "address": "Andheri Station, Mumbai, India",
      "lat": 19.12106,
      "lng": 72.84781,
      "duration": 20
    },
    {
      "address": "Borivali Station, Mumbai, India",
      "lat": 19.22969,
      "lng": 72.85757,
      "duration": 15
    },
    {
      "address": "Juhu Tara Road, Juhu, Mumbai, India",
      "lat": 19.10125,
      "lng": 72.82718,
      "duration": 10
    },
    {
      "address": "Mohammed Ali Road, Mumbai, India",
      "lat": 18.95091,
      "lng": 72.83473,
      "duration": 10
    },
    {
      "address": "Lalbaug, Parel, Mumbai, India",
      "lat": 18.99388,
      "lng": 72.8378,
      "duration": 15
    },
    {
      "address": "Dr E Moses Road, Worli, Mumbai, India",
      "lat": 18.99665,
      "lng": 72.81825,
      "duration": 10
    },
    {
      "address": "Napean Sea Road, Mumbai, India",
      "lat": 18.95526,
      "lng": 72.79863,
      "duration": 10
    },
    {
      "address": "Pedder Road, Mumbai, India",
      "lat": 18.97751,
      "lng": 72.80998,
      "duration": 20
    },
    {
      "address": "Turner Road, Bandra West, Mumbai, India",
      "lat": 19.05944,
      "lng": 72.83335,
      "duration": 10
    },
    {
      "address": "Waterfield Road, Bandra West, Mumbai, India",
      "lat": 19.06244,
      "lng": 72.83456,
      "duration": 10
    },
    {
      "address": "Pali Hill, Bandra West, Mumbai, India",
      "lat": 19.06171,
      "lng": 72.82954,
      "duration": 15
    },
    {
      "address": "EsselWorld, Gorai, Mumbai, India",
      "lat": 19.23151,
      "lng": 72.80453,
      "duration": 10
    },
    {
      "address": "Seawoods Grand Central, Navi Mumbai, India",
      "lat": 19.02121,
      "lng": 73.01754,
      "duration": 10
    },
    {
      "address": "Inorbit Mall, Vashi, Navi Mumbai, India",
      "lat": 19.06648,
      "lng": 73.00098,
      "duration": 15
    },
    {
      "address": "Chhatrapati Shivaji Maharaj Terminus, Mumbai, India",
      "lat": 18.93997,
      "lng": 72.83487,
      "duration": 20
    }
  ],
  "sao-paulo": [
    {
      "address": "MASP, Avenida Paulista, São Paulo, Brazil",
      "lat": -23.56161,
      "lng": -46.65623,
      "duration": 0
    },
    {
      "address": "Ibirapuera Park, São Paulo, Brazil",
      "lat": -23.59066,
      "lng": -46.64796,
      "duration": 10
    },
    {
      "address": "São Paulo Cathedral, Sé, São Paulo, Brazil",
      "lat": -23.55069,
      "lng": -46.6341,
      "duration": 10
    },
    {
      "address": "Estação da Luz, São Paulo, Brazil",
      "lat": -23.53478,
      "lng": -46.63516,
      "duration": 15
    },
    {
      "address": "Edifício Copan, São Paulo, Brazil",
      "lat": -23.56283,
      "lng": -46.65474,
      "duration": 10
    },
    {
      "address": "Memorial da América Latina, São Paulo, Brazil",
      "lat": -23.52702,
      "lng": -46.66552,
      "duration": 10
    },
    {
      "address": "Allianz Parque, São Paulo, Brazil",
      "lat": -23.56887,
      "lng": -46.70034,
      "duration": 15
    },
    {
      "address": "Estádio do Morumbi, São Paulo, Brazil",
      "lat": -23.59832,
      "lng": -46.71994,
      "duration": 20
    },
    {
      "address": "Arena Corinthians, São Paulo, Brazil",
      "lat": -23.54607,
      "lng": -46.47223,
      "duration": 10
    },
    {
      "address": "Shopping Iguatemi São Paulo, Brazil",
      "lat": -23.57651,
      "lng": -46.68745,
      "duration": 15
    },
    {
      "address": "Shopping Morumbi, São Paulo, Brazil",
      "lat": -23.59129,
      "lng": -46.69033,
      "duration": 10
    },
    {
      "address": "Eldorado Shopping, São Paulo, Brazil",
      "lat": -23.70798,
      "lng": -46.62343,
      "duration": 10
    },
    {
      "address": "JK Iguatemi, São Paulo, Brazil",
      "lat": -23.59172,
      "lng": -46.68914,
      "duration": 15
    },
    {
      "address": "Parque Villa-Lobos, São Paulo, Brazil",
      "lat": -23.58705,
      "lng": -46.69234,
      "duration": 10
    },
    {
      "address": "Pinacoteca de São Paulo, Brazil",
      "lat": -23.53438,
      "lng": -46.63359,
      "duration": 20
    },
    {
      "address": "Liberdade, São Paulo, Brazil",
      "lat": -23.55837,
      "lng": -46.63294,
      "duration": 15
    },
    {
      "address": "Beco do Batman, Vila Madalena, São Paulo, Brazil",
      "lat": -23.55652,
      "lng": -46.68656,
      "duration": 10
    },
    {
      "address": "Expo Center Norte, São Paulo, Brazil",
      "lat": -23.51018,
      "lng": -46.6126,
      "duration": 10
    },
    {
      "address": "Sambódromo do Anhembi, São Paulo, Brazil",
      "lat": -23.51547,
      "lng": -46.6432,
      "duration": 15
    },
    {
      "address": "Autódromo de Interlagos, São Paulo, Brazil",
      "lat": -23.70382,
      "lng": -46.70073,
      "duration": 10
    },
    {
      "address": "Vila Madalena, São Paulo, Brazil",
      "lat": -23.55119,
      "lng": -46.69711,
      "duration": 10
    },
    {
      "address": "Mercado Municipal Pinheiros, São Paulo, Brazil",
      "lat": -23.56547,
      "lng": -46.69265,
      "duration": 20
    },
    {
      "address": "Shopping Center Norte, São Paulo, Brazil",
      "lat": -23.51415,
      "lng": -46.61759,
      "duration": 10
    },
    {
      "address": "Shopping Aricanduva, São Paulo, Brazil",
      "lat": -23.56686,
      "lng": -46.50376,
      "duration": 10
    },
    {
      "address": "Shopping Anália Franco, São Paulo, Brazil",
      "lat": -23.56217,
      "lng": -46.56,
      "duration": 15
    },
    {
      "address": "Shopping Higienópolis, São Paulo, Brazil",
      "lat": -23.54121,
      "lng": -46.6569,
      "duration": 10
    },
    {
      "address": "Shopping Pátio Paulista, São Paulo, Brazil",
      "lat": -23.57044,
      "lng": -46.64382,
      "duration": 10
    },
    {
      "address": "Shopping Frei Caneca, São Paulo, Brazil",
      "lat": -23.55359,
      "lng": -46.65294,
      "duration": 15
    },
    {
      "address": "Parque Ibirapuera Auditorium, São Paulo, Brazil",
      "lat": -23.58132,
      "lng": -46.65826,
      "duration": 20
    },
    {
      "address": "Museu de Arte Contemporânea, São Paulo, Brazil",
      "lat": -23.58906,
      "lng": -46.65119,
      "duration": 10
    },
    {
      "address": "Instituto Butantan, São Paulo, Brazil",
      "lat": -23.56906,
      "lng": -46.7148,
      "duration": 15
    },
    {
      "address": "Hospital das Clínicas, São Paulo, Brazil",
      "lat": -23.55718,
      "lng": -46.66988,
      "duration": 10
    },
    {
      "address": "Universidade de São Paulo, São Paulo, Brazil",
      "lat": -23.56366,
      "lng": -46.72003,
      "duration": 10
    },
    {
      "address": "Parque do Piqueri, São Paulo, Brazil",
      "lat": -23.52961,
      "lng": -46.57571,
      "duration": 15
    },
    {
      "address": "Parque da Água Branca, São Paulo, Brazil",
      "lat": -23.52995,
      "lng": -46.6674,
      "duration": 10
    },
    {
      "address": "Parque Burle Marx, São Paulo, Brazil",
      "lat": -23.63386,
      "lng": -46.72174,
      "duration": 20
    },
    {
      "address": "Parque Trianon, São Paulo, Brazil",
      "lat": -23.56166,
      "lng": -46.65786,
      "duration": 15
    },
    {
      "address": "Mosteiro de São Bento, São Paulo, Brazil",
      "lat": -23.5532,
      "lng": -46.71807,
      "duration": 10
    },
    {
      "address": "Pátio do Colégio, São Paulo, Brazil",
      "lat": -23.57028,
      "lng": -46.57818,
      "duration": 10
    },
    {
      "address": "Mercado de Pinheiros, São Paulo, Brazil",
      "lat": -23.56729,
      "lng": -46.70026,
      "duration": 15
    },
    {
      "address": "Rua Oscar Freire, São Paulo, Brazil",
      "lat": -23.56321,
      "lng": -46.66889,
      "duration": 10
    },
    {
      "address": "Rua Augusta, São Paulo, Brazil",
      "lat": -23.55487,
      "lng": -46.65672,
      "duration": 10
    },
    {
      "address": "Avenida Brigadeiro Faria Lima, São Paulo, Brazil",
      "lat": -23.57814,
      "lng": -46.68627,
      "duration": 20
    },
    {
      "address": "Marginal Pinheiros, São Paulo, Brazil",
      "lat": -23.55286,
      "lng": -46.7247,
      "duration": 10
    },
    {
      "address": "Estação Pinheiros, São Paulo, Brazil",
      "lat": -23.55936,
      "lng": -46.69053,
      "duration": 10
    },
    {
      "address": "Pinheiros, São Paulo, Brazil",
      "lat": -23.56172,
      "lng": -46.68617,
      "duration": 15
    },
    {
      "address": "Moema, São Paulo, Brazil",
      "lat": -23.60605,
      "lng": -46.66367,
      "duration": 10
    },
    {
      "address": "Mercado Municipal, São Paulo, Brazil",
      "lat": -23.54144,
      "lng": -46.62992,
      "duration": 10
    },
    {
      "address": "Theatro Municipal, São Paulo, Brazil",
      "lat": -23.5458,
      "lng": -46.63883,
      "duration": 15
    },
    {
      "address": "Parque Ibirapuera, São Paulo, Brazil",
      "lat": -23.58857,
      "lng": -46.65563,
      "duration": 20
    }
  ]
};
